/**
 * Vintiz receipt fidelity footer (charte v2).
 *
 * Mirrors the ESC/POS text generated by the backend
 * (apps/api/app/services/receipt.py). Use this React variant for
 * print previews / web tickets — it renders identical wording so
 * customers see the same copy across paper and screen.
 */

interface BaseProps {
  /** Currency: TTC total of the cart in euros. */
  totalTtc: number;
}

interface MemberProps extends BaseProps {
  variant: "member";
  firstName: string;
  lastName: string;
  /** V###### loyalty card number. */
  membershipNumber: string;
  /** Current balance after this sale. */
  pointsBalance: number;
  /** Points earned on this very sale. */
  pointsEarned: number;
}

interface NonMemberProps extends BaseProps {
  variant: "non-member";
  /** Optional override; defaults to 1 €=1 pt rounded down. */
  wouldEarn?: number;
}

export type ReceiptFooterProps = MemberProps | NonMemberProps;

const POINT_PER_EURO = 1;

export function ReceiptFooter(props: ReceiptFooterProps) {
  if (props.variant === "member") {
    return (
      <section className="font-mono text-xs text-black border-t border-black/20 mt-3 pt-2 text-center">
        <h3 className="font-display font-semibold uppercase tracking-wider mb-2">
          --- Fidélité Vintiz ---
        </h3>
        <p>
          Membre :{" "}
          <strong>
            {props.firstName} {props.lastName}
          </strong>
        </p>
        <p>N° {props.membershipNumber}</p>
        <p>
          Solde : {props.pointsBalance} pts
          {props.pointsEarned > 0 && ` (+${props.pointsEarned} sur cet achat)`}
        </p>
      </section>
    );
  }

  const wouldEarn =
    props.wouldEarn ?? Math.max(0, Math.floor(props.totalTtc) * POINT_PER_EURO);

  return (
    <section className="font-mono text-xs text-black border-t border-black/20 mt-3 pt-2 text-center">
      <h3 className="font-display font-semibold uppercase tracking-wider mb-2">
        --- Fidélité Vintiz ---
      </h3>
      {wouldEarn > 0 && <p>Vous auriez gagné {wouldEarn} pts.</p>}
      <p>Adhérez gratuitement à votre prochain passage</p>
      <p>Carte digitale Apple/Google Wallet</p>
    </section>
  );
}
