"""Window-display proposals (P2-007).

Each Monday at 06:00 the cron stores one ``WindowDisplayProposal`` for
the running ISO week. Sophie reviews it on the dashboard, edits if
needed, then taps "Validée" — at which point ``accepted_at`` is stamped
and the proposal becomes the source of truth for that week's window.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base
from app.models.types import JSONType, UUIDType


class WindowDisplayProposal(Base):
    __tablename__ = "window_display_proposals"

    # ISO-week key: "2026-W18". Unique so the cron can upsert idempotently.
    iso_week: Mapped[str] = mapped_column(
        String(8), unique=True, nullable=False
    )
    # Free-form payload — typically:
    # {
    #   "theme": "Pastels printaniers",
    #   "color_palette": ["#fce4ec", "#bbdefb", "#fff9c4"],
    #   "items": [
    #     {"product_id": "...", "position": "central", "rationale": "..."}
    #   ]
    # }
    proposal: Mapped[dict] = mapped_column(JSONType, nullable=False)
    # Soft signal — was the proposal generated by Claude (true) or by the
    # deterministic fallback (false)?
    used_llm: Mapped[bool] = mapped_column(default=False, nullable=False)
    accepted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    accepted_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUIDType, ForeignKey("users.id"), nullable=True
    )
