"""Weekly checklist tasks (Lot 4 — automatisation hebdo).

Each row is a single task surfaced to the manager in the Companion IA
checklist. Generated by the cron jobs in ``app/jobs.py``.
"""

from __future__ import annotations

import enum
import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, Enum, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base
from app.models.types import JSONType


class WeeklyTaskKind(str, enum.Enum):
    monday_scoring_update = "monday_scoring_update"
    morning_restock = "morning_restock"
    tuesday_window_refresh = "tuesday_window_refresh"
    wednesday_featured_refresh = "wednesday_featured_refresh"
    thursday_six_weeks_exit = "thursday_six_weeks_exit"


class WeeklyTaskStatus(str, enum.Enum):
    pending = "pending"
    done = "done"
    skipped = "skipped"


class WeeklyTask(Base):
    __tablename__ = "weekly_tasks"

    kind: Mapped[WeeklyTaskKind] = mapped_column(
        Enum(WeeklyTaskKind, name="weekly_task_kind"), nullable=False
    )
    scheduled_for: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[WeeklyTaskStatus] = mapped_column(
        Enum(WeeklyTaskStatus, name="weekly_task_status"),
        nullable=False,
        default=WeeklyTaskStatus.pending,
    )
    payload: Mapped[dict] = mapped_column(JSONType, nullable=False, default=dict)
    completed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    notes: Mapped[str | None] = mapped_column(String(500), nullable=True)
