import uuid
from datetime import datetime, timedelta, timezone
from decimal import Decimal

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import (
    CartEmpty, InsufficientBalance, InvalidOperation, PaymentShortfall,
    ProductNotAvailable, ResourceNotFound,
)

from app.models.client import AvoirTransaction, AvoirTxType, Client
from app.models.pos import (
    CashDrawer,
    Payment,
    PaymentMethod,
    Transaction,
    TransactionItem,
    TransactionType,
)
from app.models.product import Product, ProductStatus


class PosService:
    """Business logic for point-of-sale operations."""

    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    # ------------------------------------------------------------------
    # Transactions
    # ------------------------------------------------------------------

    async def create_transaction(
        self,
        user_id: uuid.UUID,
        items: list,
        payments: list,
        client_id: uuid.UUID | None = None,
        cashier_id: uuid.UUID | None = None,
        client_uuid: uuid.UUID | None = None,
    ) -> Transaction:
        """Create a sale transaction.

        Supports two kinds of cart items:
        - Product items: have product_id → validates product, marks as sold
        - Manual items: no product_id, just name + unit_price (e.g. sac)

        Applies discount_percent per item if provided.

        ``client_uuid`` is generated by the POS UI before the first submit
        attempt (P1-005). When supplied, a duplicate POST that carries
        the same UUID short-circuits and returns the existing
        transaction unchanged — making offline-replay safe.
        """
        # Idempotence short-circuit: a previous attempt may have succeeded
        # before the client could acknowledge it. Returning the existing
        # row keeps replay safe.
        if client_uuid is not None:
            existing_row = await self.db.execute(
                select(Transaction).where(
                    Transaction.client_uuid == client_uuid
                )
            )
            existing = existing_row.scalar_one_or_none()
            if existing is not None:
                return existing

        if not items:
            raise CartEmpty()

        total_ttc = Decimal("0")
        # (product | None, quantity, unit_price, discount_percent, item_name)
        line_rows: list[tuple[Product | None, int, Decimal, float, str]] = []

        for cart_item in items:
            if cart_item.product_id:
                result = await self.db.execute(
                    select(Product).where(Product.id == cart_item.product_id)
                )
                product = result.scalar_one_or_none()
                if product is None:
                    raise ResourceNotFound("Product", cart_item.product_id)
                if product.status not in (ProductStatus.display, ProductStatus.stock):
                    raise ProductNotAvailable(product.name, product.status.value)
                unit_price = Decimal(str(cart_item.unit_price)) if cart_item.unit_price else Decimal(str(product.sale_price))
                discount = cart_item.discount_percent or 0
                line_total = (unit_price * cart_item.quantity * (Decimal("100") - Decimal(str(discount))) / Decimal("100")).quantize(Decimal("0.01"))
                total_ttc += line_total
                line_rows.append((product, cart_item.quantity, unit_price, discount, product.name))
            else:
                # Manual item (e.g. sac)
                if not cart_item.name or not cart_item.unit_price:
                    raise InvalidOperation("Manual items require name and unit_price")
                unit_price = Decimal(str(cart_item.unit_price))
                discount = cart_item.discount_percent or 0
                line_total = (unit_price * cart_item.quantity * (Decimal("100") - Decimal(str(discount))) / Decimal("100")).quantize(Decimal("0.01"))
                total_ttc += line_total
                line_rows.append((None, cart_item.quantity, unit_price, discount, cart_item.name))

        # TVA 20 %: HT = TTC / 1.20, TVA = TTC - HT
        total_ht = (total_ttc / Decimal("1.20")).quantize(Decimal("0.01"))
        total_tva = (total_ttc - total_ht).quantize(Decimal("0.01"))

        # Validate payments
        total_paid = sum(Decimal(str(p.amount)) for p in payments)
        if total_paid < total_ttc:
            raise PaymentShortfall(total_paid, total_ttc)

        # Generate transaction number.
        # On PostgreSQL use the dedicated sequence (NF525 — no gaps under concurrency).
        # On SQLite (tests) fall back to MAX+1 because sequences don't exist.
        from sqlalchemy import text
        dialect = self.db.bind.dialect.name if self.db.bind else "postgresql"
        if dialect == "sqlite":
            max_num_result = await self.db.execute(
                select(func.coalesce(func.max(Transaction.transaction_number), 0))
            )
            next_number = max_num_result.scalar_one() + 1
        else:
            seq_result = await self.db.execute(
                text("SELECT nextval('transaction_number_seq')")
            )
            next_number = seq_result.scalar_one()

        transaction = Transaction(
            transaction_number=next_number,
            transaction_type=TransactionType.sale,
            user_id=user_id,
            cashier_id=cashier_id,
            client_id=client_id,
            client_uuid=client_uuid,
            total_ht=float(total_ht),
            total_tva=float(total_tva),
            total_ttc=float(total_ttc),
            hash_chain="",  # will be set by FiscalService
        )
        self.db.add(transaction)
        await self.db.flush()

        # Create transaction items
        for product, quantity, unit_price, discount, _name in line_rows:
            line_total = (unit_price * quantity * (Decimal("100") - Decimal(str(discount))) / Decimal("100")).quantize(Decimal("0.01"))
            item = TransactionItem(
                transaction_id=transaction.id,
                product_id=product.id if product else None,
                quantity=quantity,
                unit_price=float(unit_price),
                discount_percent=discount,
                line_total=float(line_total),
            )
            self.db.add(item)

            # Mark product as sold (only real products)
            if product:
                product.status = ProductStatus.sold
                product.sold_at = datetime.now(timezone.utc)

        # Create payment records
        method_map = {
            "especes": "cash", "carte": "card", "cheque": "cheque",
            "cash": "cash", "card": "card", "avoir": "avoir",
        }
        avoir_total = Decimal("0")
        for pay in payments:
            method_str = method_map.get(pay.method, pay.method)
            method_enum = PaymentMethod(method_str)
            payment = Payment(
                transaction_id=transaction.id,
                method=method_enum,
                amount=float(pay.amount),
            )
            self.db.add(payment)
            if method_enum == PaymentMethod.avoir:
                avoir_total += Decimal(str(pay.amount))

        # Avoir checkout: validate balance, debit client and write ledger.
        if avoir_total > 0:
            if client_id is None:
                raise InvalidOperation("Avoir payment requires a client to be selected")
            client_result = await self.db.execute(
                select(Client).where(Client.id == client_id)
            )
            client = client_result.scalar_one_or_none()
            if client is None:
                raise ResourceNotFound("Client", client_id)
            current_balance = Decimal(str(client.avoir_credit or 0))
            if avoir_total > current_balance:
                raise InsufficientBalance(
                    f"Avoir: requested {avoir_total}, available {current_balance}"
                )
            client.avoir_credit = float(current_balance - avoir_total)
            self.db.add(
                AvoirTransaction(
                    client_id=client.id,
                    transaction_id=transaction.id,
                    tx_type=AvoirTxType.debit,
                    amount=float(avoir_total),
                    reason=f"Sale #{transaction.transaction_number}",
                )
            )

        await self.db.flush()
        await self.db.refresh(transaction)
        return transaction

    async def list_transactions(
        self, skip: int = 0, limit: int = 50
    ) -> list[dict]:
        """Return a paginated list of transactions."""
        result = await self.db.execute(
            select(Transaction)
            .order_by(Transaction.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        transactions = result.scalars().all()
        return [
            {
                "id": str(t.id),
                "transaction_number": t.transaction_number,
                "transaction_type": t.transaction_type.value,
                "total_ttc": float(t.total_ttc),
                "total_ht": float(t.total_ht),
                "total_tva": float(t.total_tva),
                "created_at": t.created_at.isoformat() if t.created_at else None,
                "item_count": len(t.items) if t.items else 0,
            }
            for t in transactions
        ]

    async def get_transaction(self, transaction_id: uuid.UUID) -> dict | None:
        """Return a single transaction with items, payments, and client info."""
        from app.models.client import Client
        result = await self.db.execute(
            select(Transaction).where(Transaction.id == transaction_id)
        )
        t = result.scalar_one_or_none()
        if t is None:
            return None

        # Build product name map for items that have a product_id
        product_ids = [item.product_id for item in (t.items or []) if item.product_id]
        product_names: dict[str, str] = {}
        if product_ids:
            prod_result = await self.db.execute(
                select(Product.id, Product.name).where(Product.id.in_(product_ids))
            )
            for pid, pname in prod_result.all():
                product_names[str(pid)] = pname

        # Load client if present
        client_data = None
        if t.client_id:
            c_result = await self.db.execute(
                select(Client).where(Client.id == t.client_id)
            )
            client = c_result.scalar_one_or_none()
            if client:
                client_data = {
                    "id": str(client.id),
                    "first_name": client.first_name,
                    "last_name": client.last_name,
                    "email": client.email,
                    "phone": client.phone,
                }

        return {
            "id": str(t.id),
            "transaction_number": t.transaction_number,
            "type": t.transaction_type.value,
            "total_ttc": float(t.total_ttc),
            "total_ht": float(t.total_ht),
            "tax_amount": float(t.total_tva),
            "hash_chain": t.hash_chain,
            "cashier_id": str(t.cashier_id) if t.cashier_id else None,
            "created_at": t.created_at.isoformat() if t.created_at else None,
            "client": client_data,
            "items": [
                {
                    "id": str(item.id),
                    "product_id": str(item.product_id) if item.product_id else None,
                    "name": product_names.get(str(item.product_id), "Article") if item.product_id else "Article",
                    "quantity": item.quantity,
                    "unit_price": float(item.unit_price),
                    "discount_percent": float(item.discount_percent),
                    "line_total": float(item.line_total),
                }
                for item in (t.items or [])
            ],
            "payments": [
                {
                    "id": str(p.id),
                    "method": p.method.value,
                    "amount": float(p.amount),
                }
                for p in (t.payments or [])
            ],
        }

    # ------------------------------------------------------------------
    # Cash Drawer
    # ------------------------------------------------------------------

    async def open_drawer(
        self,
        user_id: uuid.UUID,
        opening_amount: Decimal,
        cashier_id: uuid.UUID | None = None,
    ) -> CashDrawer:
        """Open a new cash drawer. Raises if one is already open."""
        existing = await self.get_open_drawer()
        if existing:
            raise InvalidOperation("A cash drawer is already open")
        drawer = CashDrawer(
            user_id=user_id,
            cashier_id=cashier_id,
            opened_at=datetime.now(timezone.utc),
            opening_amount=float(opening_amount),
            is_open=True,
        )
        self.db.add(drawer)
        await self.db.flush()
        await self.db.refresh(drawer)
        return drawer

    async def close_drawer(
        self,
        user_id: uuid.UUID,
        closing_amount: Decimal,
        cashier_id: uuid.UUID | None = None,
    ) -> CashDrawer:
        """Close the currently open drawer.

        Computes *expected_amount* as opening_amount + sum of cash payments
        made while the drawer was open. If a cashier_id is supplied, it
        replaces the one set at opening (e.g. shift handover).
        """
        drawer = await self.get_open_drawer()
        if not drawer:
            raise ResourceNotFound("CashDrawer")
        if cashier_id is not None:
            drawer.cashier_id = cashier_id

        # Sum cash payments during the drawer period
        cash_sum_result = await self.db.execute(
            select(func.coalesce(func.sum(Payment.amount), 0))
            .join(Transaction, Payment.transaction_id == Transaction.id)
            .where(
                Payment.method == PaymentMethod.cash,
                Transaction.created_at >= drawer.opened_at,
            )
        )
        cash_total = Decimal(str(cash_sum_result.scalar_one()))

        drawer.closing_amount = float(closing_amount)
        drawer.expected_amount = float(
            Decimal(str(drawer.opening_amount)) + cash_total
        )
        drawer.closed_at = datetime.now(timezone.utc)
        drawer.is_open = False

        await self.db.flush()
        await self.db.refresh(drawer)
        return drawer

    async def get_open_drawer(self) -> CashDrawer | None:
        """Return the currently open cash drawer, or None."""
        result = await self.db.execute(
            select(CashDrawer).where(CashDrawer.is_open.is_(True)).limit(1)
        )
        return result.scalar_one_or_none()

    async def finalize_sale(
        self,
        transaction: Transaction,
        *,
        coupon_code: str | None,
        user_id: uuid.UUID,
    ) -> None:
        """Post-sign finalization: coupon redemption + loyalty + analytics events.

        Called from the router after FiscalService.sign_transaction(). Failures in
        any step are logged and swallowed — they never roll back the signed sale.
        """
        import logging as _logging
        _log = _logging.getLogger("vintiz")

        # Coupon redemption
        if coupon_code:
            from app.services.coupon import CouponError, redeem_coupon, validate_coupon
            try:
                preview = await validate_coupon(
                    self.db,
                    code=coupon_code,
                    cart_total=float(transaction.total_ttc),
                    client_id=transaction.client_id,
                )
                await redeem_coupon(self.db, preview.coupon_id, transaction.id)
            except CouponError as exc:
                _log.warning(
                    "Coupon redemption failed for tx=%s code=%s reason=%s",
                    transaction.id, coupon_code, exc,
                )

        # Loyalty: 1 € = 1 pt; every 100 pts crossed → 8 € coupon (60d, auto)
        if transaction.client_id is not None:
            try:
                await self._credit_loyalty_and_emit_milestones(transaction)
            except Exception as exc:  # noqa: BLE001
                _log.warning(
                    "Loyalty milestone hook failed for tx=%s: %s",
                    transaction.id, exc,
                )

        # Emit analytics events (P1-003)
        from app.models.events import EventSource, EventType
        from app.services.events import EventService
        events = EventService(self.db)
        if transaction.client_id is not None:
            await events.emit(
                EventType.customer_visited,
                source=EventSource.pos,
                customer_id=transaction.client_id,
                transaction_id=transaction.id,
                user_id=user_id,
            )
        for item in (transaction.items or []):
            if item.product_id is None:
                continue
            await events.emit(
                EventType.product_sold,
                source=EventSource.pos,
                customer_id=transaction.client_id,
                product_id=item.product_id,
                transaction_id=transaction.id,
                user_id=user_id,
                meta={
                    "quantity": int(item.quantity),
                    "unit_price": float(item.unit_price),
                    "discount_percent": float(item.discount_percent or 0),
                },
            )

    # ------------------------------------------------------------------
    # Loyalty (1 € = 1 pt, 100 pts = 8 € auto)
    # ------------------------------------------------------------------

    async def _credit_loyalty_and_emit_milestones(
        self, transaction: Transaction
    ) -> None:
        """Credit points + emit milestone coupons.

        Only invoked when the sale has a client. Loads/creates the
        ``LoyaltyAccount`` lazily so unenrolled clients still earn points
        from the moment they share their email.
        """
        from app.models.client import (
            LoyaltyAccount,
            LoyaltyTransaction,
            LoyaltyTxType,
        )
        from app.models.coupon import Coupon, CouponDiscountType, CouponSource
        from app.services.coupon import _draw_unique_code  # collision-safe helper
        from app.services.offers_engine import (
            LOYALTY_VOUCHER_VALID_DAYS,
            LOYALTY_VOUCHER_VALUE,
            milestones_crossed,
            points_to_credit,
        )

        amount = float(transaction.total_ttc or 0)
        points = points_to_credit(amount)
        if points <= 0:
            return

        result = await self.db.execute(
            select(LoyaltyAccount).where(
                LoyaltyAccount.client_id == transaction.client_id
            )
        )
        account = result.scalar_one_or_none()
        if account is None:
            from app.services.membership_id import generate_membership_number

            membership = await generate_membership_number(self.db)
            account = LoyaltyAccount(
                client_id=transaction.client_id,
                points=0,
                membership_number=membership,
            )
            self.db.add(account)
            await self.db.flush()

        # Idempotency guard: a replay (e.g. router crash between flush and
        # commit on the first attempt) must NOT credit the same sale twice.
        # The earn ledger row is keyed by the unique transaction_number.
        sale_marker = f"Sale #{transaction.transaction_number}"
        already = await self.db.execute(
            select(LoyaltyTransaction.id).where(
                LoyaltyTransaction.account_id == account.id,
                LoyaltyTransaction.tx_type == LoyaltyTxType.earn,
                LoyaltyTransaction.description == sale_marker,
            ).limit(1)
        )
        if already.scalar_one_or_none() is not None:
            return

        before = int(account.points or 0)
        account.points = before + points
        self.db.add(LoyaltyTransaction(
            account_id=account.id,
            tx_type=LoyaltyTxType.earn,
            points=points,
            description=sale_marker,
        ))

        crossed = milestones_crossed(before, account.points)
        if crossed <= 0:
            return

        now = datetime.now(timezone.utc)
        valid_until = now + timedelta(days=LOYALTY_VOUCHER_VALID_DAYS)
        for _ in range(crossed):
            code = await _draw_unique_code(self.db, "LOYAL")
            self.db.add(Coupon(
                code=code,
                client_id=transaction.client_id,
                discount_type=CouponDiscountType.amount,
                discount_value=LOYALTY_VOUCHER_VALUE,
                source=CouponSource.loyalty_milestone,
                valid_from=now,
                valid_until=valid_until,
                is_active=True,
                notes=f"Palier {LOYALTY_VOUCHER_VALUE:.0f} € — atteint sur tx #{transaction.transaction_number}",
            ))
