import logging
import uuid
from datetime import datetime, timedelta, timezone
from decimal import Decimal

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger("vintiz")

from app.core.exceptions import (
    CartEmpty, InsufficientBalance, InvalidOperation, PaymentShortfall,
    ProductNotAvailable, ResourceNotFound,
)

from app.models.client import AvoirTransaction, AvoirTxType, Client
from app.models.pos import (
    CashDrawer,
    Payment,
    PaymentMethod,
    Transaction,
    TransactionItem,
    TransactionType,
)
from app.models.permanent_item import PermanentItem
from app.models.product import Product, ProductStatus


class PosService:
    """Business logic for point-of-sale operations."""

    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    # ------------------------------------------------------------------
    # Transactions
    # ------------------------------------------------------------------

    async def create_transaction(
        self,
        user_id: uuid.UUID,
        items: list,
        payments: list,
        client_id: uuid.UUID | None = None,
        cashier_id: uuid.UUID | None = None,
        client_uuid: uuid.UUID | None = None,
        is_invoice: bool = False,
        client_siret: str | None = None,
        client_company_name: str | None = None,
        client_billing_address: str | None = None,
        template_id: uuid.UUID | None = None,
    ) -> Transaction:
        """Create a sale transaction.

        Supports two kinds of cart items:
        - Product items: have product_id → validates product, marks as sold
        - Manual items: no product_id, just name + unit_price (e.g. sac)

        Applies discount_percent per item if provided.

        ``client_uuid`` is generated by the POS UI before the first submit
        attempt (P1-005). When supplied, a duplicate POST that carries
        the same UUID short-circuits and returns the existing
        transaction unchanged — making offline-replay safe.
        """
        # Idempotence short-circuit: a previous attempt may have succeeded
        # before the client could acknowledge it. Returning the existing
        # row keeps replay safe.
        if client_uuid is not None:
            existing_row = await self.db.execute(
                select(Transaction).where(
                    Transaction.client_uuid == client_uuid
                )
            )
            existing = existing_row.scalar_one_or_none()
            if existing is not None:
                return existing

        if not items:
            raise CartEmpty()

        # B2B invoice mode requires the buyer block to be filled — DGFiP
        # mandates company name, SIRET (14 digits) and billing address on every
        # commercial invoice.
        if is_invoice:
            if not (client_company_name and client_company_name.strip()):
                raise InvalidOperation(
                    "Facture B2B : raison sociale obligatoire"
                )
            siret_digits = (client_siret or "").strip()
            if not (siret_digits.isdigit() and len(siret_digits) == 14):
                raise InvalidOperation(
                    "Facture B2B : SIRET invalide (14 chiffres requis)"
                )
            if not (client_billing_address and client_billing_address.strip()):
                raise InvalidOperation(
                    "Facture B2B : adresse de facturation obligatoire"
                )

        # Pass 1 — résoudre chaque ligne (produit / article permanent / manuel)
        # avec sa remise MANUELLE éventuelle. La remise opération (Solde) est
        # appliquée dans un 2ᵉ temps sur les pièces d'inventaire les moins chères.
        resolved: list[dict] = []
        for cart_item in items:
            if cart_item.product_id:
                result = await self.db.execute(
                    select(Product).where(Product.id == cart_item.product_id)
                )
                product = result.scalar_one_or_none()
                if product is None:
                    raise ResourceNotFound("Product", cart_item.product_id)
                # On peut vendre une pièce où qu'elle soit dans le cycle de vie
                # (réserve OU rayon) : un article encore en stock est vendable.
                # On ne bloque que les statuts réellement non-vendables : déjà
                # vendu, retiré (returned) ou donné (donated).
                if product.status in (
                    ProductStatus.sold,
                    ProductStatus.returned,
                    ProductStatus.donated,
                    ProductStatus.returned_to_sorting,
                    ProductStatus.rejected,
                ):
                    raise ProductNotAvailable(product.name, product.status.value)
                unit_price = Decimal(str(cart_item.unit_price)) if cart_item.unit_price else Decimal(str(product.sale_price))
                discount = cart_item.discount_percent or 0
                resolved.append({
                    "product": product, "perm": None,
                    "quantity": cart_item.quantity, "unit_price": unit_price,
                    "manual_discount": float(discount), "name": product.name,
                })
            elif getattr(cart_item, "permanent_item_id", None):
                # Article permanent (quantité illimitée) — pas de check de stock
                # ni de marquage ``sold``. Le même code-barres peut être passé
                # plusieurs fois sur la même vente.
                perm_id = cart_item.permanent_item_id
                result = await self.db.execute(
                    select(PermanentItem).where(PermanentItem.id == perm_id)
                )
                perm = result.scalar_one_or_none()
                if perm is None:
                    raise ResourceNotFound("PermanentItem", perm_id)
                if not perm.is_active:
                    raise ProductNotAvailable(perm.name, "désactivé")
                unit_price = Decimal(str(cart_item.unit_price)) if cart_item.unit_price else Decimal(str(perm.sale_price))
                discount = cart_item.discount_percent or 0
                resolved.append({
                    "product": None, "perm": perm,
                    "quantity": cart_item.quantity, "unit_price": unit_price,
                    "manual_discount": float(discount), "name": perm.name,
                })
            else:
                # Manual item (e.g. sac)
                if not cart_item.name or not cart_item.unit_price:
                    raise InvalidOperation("Manual items require name and unit_price")
                unit_price = Decimal(str(cart_item.unit_price))
                discount = cart_item.discount_percent or 0
                resolved.append({
                    "product": None, "perm": None,
                    "quantity": cart_item.quantity, "unit_price": unit_price,
                    "manual_discount": float(discount), "name": cart_item.name,
                })

        # Pass 2 — Solde : remise automatique sur les pièces d'inventaire les
        # moins chères (paquets de 6 → 3 à -50 %, paires → 1 à -30 %). Calculée
        # sur le prix unitaire APRÈS remise manuelle. Source unique de vérité
        # partagée avec l'aperçu POS (solde_engine).
        from app.services.solde_engine import (
            compute_solde_rates,
            get_active_solde,
            solde_config_from_offer,
        )

        solde_pct_by_line: dict[int, float] = {}
        solde_offer = await get_active_solde(self.db)
        if solde_offer is not None:
            cfg = solde_config_from_offer(solde_offer)
            unit_owner: list[int] = []
            unit_prices: list[float] = []
            for ridx, row in enumerate(resolved):
                if row["product"] is None:
                    continue  # Solde uniquement sur les pièces d'inventaire
                per_unit = float(row["unit_price"]) * (1 - row["manual_discount"] / 100.0)
                for _ in range(max(1, int(row["quantity"]))):
                    unit_owner.append(ridx)
                    unit_prices.append(per_unit)
            rates = compute_solde_rates(unit_prices, cfg)
            # Toutes les unités d'une même ligne ont le même prix → le taux
            # moyen appliqué au total ligne est exact.
            accum: dict[int, list[float]] = {}
            for owner, rate in zip(unit_owner, rates):
                accum.setdefault(owner, []).append(rate)
            for ridx, rate_list in accum.items():
                solde_pct_by_line[ridx] = sum(rate_list) / len(rate_list)

        # Pass 3 — calculer les totaux + marquer les lignes promotionnelles.
        # (product | None, permanent_item | None, quantity, unit_price,
        #  discount_percent, item_name, promotional, line_total)
        total_ttc = Decimal("0")
        line_rows: list[
            tuple[Product | None, PermanentItem | None, int, Decimal, float, str, bool, Decimal]
        ] = []
        for ridx, row in enumerate(resolved):
            unit_price = row["unit_price"]
            quantity = row["quantity"]
            manual_discount = row["manual_discount"]
            solde_pct = solde_pct_by_line.get(ridx, 0.0)
            gross = unit_price * Decimal(str(quantity))
            line_total = (
                gross
                * (Decimal("100") - Decimal(str(manual_discount))) / Decimal("100")
                * (Decimal("100") - Decimal(str(solde_pct))) / Decimal("100")
            ).quantize(Decimal("0.01"))
            # Remise effective combinée (manuelle + solde) figée sur la ligne.
            effective_discount = (
                float((Decimal("1") - (line_total / gross)) * Decimal("100"))
                if gross > 0 else 0.0
            )
            product = row["product"]
            # Promotionnel = remise solde appliquée OU produit déjà démarqué
            # (statut discounted / deep_discounted). Ces lignes ne cotisent pas
            # de points de fidélité.
            promotional = solde_pct > 0 or (
                product is not None
                and product.status in (
                    ProductStatus.discounted,
                    ProductStatus.deep_discounted,
                )
            )
            total_ttc += line_total
            line_rows.append((
                product, row["perm"], quantity, unit_price,
                round(effective_discount, 2), row["name"], promotional, line_total,
            ))

        # TVA 20 %: HT = TTC / 1.20, TVA = TTC - HT
        total_ht = (total_ttc / Decimal("1.20")).quantize(Decimal("0.01"))
        total_tva = (total_ttc - total_ht).quantize(Decimal("0.01"))

        # Validate payments
        total_paid = sum(Decimal(str(p.amount)) for p in payments)
        if total_paid < total_ttc:
            raise PaymentShortfall(total_paid, total_ttc)

        # Generate transaction number.
        # On PostgreSQL use the dedicated sequence (NF525 — no gaps under concurrency).
        # On SQLite (tests) fall back to MAX+1 because sequences don't exist.
        from sqlalchemy import text
        dialect = self.db.bind.dialect.name if self.db.bind else "postgresql"
        if dialect == "sqlite":
            max_num_result = await self.db.execute(
                select(func.coalesce(func.max(Transaction.transaction_number), 0))
            )
            next_number = max_num_result.scalar_one() + 1
        else:
            seq_result = await self.db.execute(
                text("SELECT nextval('transaction_number_seq')")
            )
            next_number = seq_result.scalar_one()

        # B2B invoice numbering — separate sequence so tickets and invoices
        # don't interleave (NF525 + DGFiP requirement). On SQLite tests the
        # sequence doesn't exist so we fall back to MAX+1.
        invoice_number: int | None = None
        if is_invoice:
            if dialect == "sqlite":
                inv_result = await self.db.execute(
                    select(func.coalesce(func.max(Transaction.invoice_number), 0))
                )
                invoice_number = inv_result.scalar_one() + 1
            else:
                inv_seq = await self.db.execute(
                    text("SELECT nextval('invoice_number_seq')")
                )
                invoice_number = inv_seq.scalar_one()

        transaction = Transaction(
            transaction_number=next_number,
            transaction_type=TransactionType.sale,
            user_id=user_id,
            cashier_id=cashier_id,
            client_id=client_id,
            client_uuid=client_uuid,
            total_ht=float(total_ht),
            total_tva=float(total_tva),
            total_ttc=float(total_ttc),
            hash_chain="",  # will be set by FiscalService
            is_invoice=is_invoice,
            invoice_number=invoice_number,
            client_siret=(client_siret.strip() if client_siret else None),
            client_company_name=(
                client_company_name.strip() if client_company_name else None
            ),
            client_billing_address=(
                client_billing_address.strip() if client_billing_address else None
            ),
            template_id=template_id,
        )
        self.db.add(transaction)
        await self.db.flush()

        # Create transaction items
        for product, perm_item, quantity, unit_price, discount, _name, promotional, line_total in line_rows:
            item = TransactionItem(
                transaction_id=transaction.id,
                product_id=product.id if product else None,
                permanent_item_id=perm_item.id if perm_item else None,
                product_name=(product.name if product else (perm_item.name if perm_item else _name)),
                quantity=quantity,
                unit_price=float(unit_price),
                discount_percent=discount,
                line_total=float(line_total),
                promotional=promotional,
            )
            self.db.add(item)

            # Mark product as sold (only real products — un article permanent
            # garde sa quantité illimitée).
            if product:
                product.status = ProductStatus.sold
                product.sold_at = datetime.now(timezone.utc)

        # Create payment records
        method_map = {
            "especes": "cash", "carte": "card", "cheque": "cheque",
            "cash": "cash", "card": "card", "avoir": "avoir",
            "cheque_cdc": "cheque_cdc",
            "voucher": "voucher", "bon": "voucher",
        }
        avoir_total = Decimal("0")
        # Bons cadeau affectés comme moyen de paiement : (montant, code).
        voucher_tenders: list[tuple[Decimal, str | None]] = []
        for pay in payments:
            method_str = method_map.get(pay.method, pay.method)
            method_enum = PaymentMethod(method_str)
            payment = Payment(
                transaction_id=transaction.id,
                method=method_enum,
                amount=float(pay.amount),
            )
            # Persist SumUp identifiers on card tenders so a later refund can
            # be issued via the SumUp API. The attributes are optional on the
            # DTO (only the POS card flow sets them); guard with getattr so
            # other callers (seed scripts, offline replay) keep working.
            if method_enum == PaymentMethod.card:
                for _attr in (
                    "sumup_checkout_id", "sumup_transaction_id",
                    "sumup_transaction_code", "sumup_auth_code",
                    "sumup_card_brand", "sumup_card_last4", "sumup_environment",
                ):
                    _val = getattr(pay, _attr, None)
                    if _val:
                        setattr(payment, _attr, _val)
            self.db.add(payment)
            if method_enum == PaymentMethod.avoir:
                avoir_total += Decimal(str(pay.amount))
            elif method_enum == PaymentMethod.voucher:
                voucher_tenders.append(
                    (Decimal(str(pay.amount)), getattr(pay, "voucher_code", None))
                )

        # Bon cadeau (ouverture) débité comme moyen de paiement : on valide le
        # bon contre le panier, on vérifie que le montant affecté ne dépasse pas
        # sa valeur, puis on le marque consommé (lié à la vente). Le bon compte
        # dans ``total_paid`` → il réduit le reste à régler en espèces / CB.
        if voucher_tenders:
            if len(voucher_tenders) > 1:
                # Un seul bon cadeau événementiel par transaction : empiler
                # deux bons sur la même vente est interdit côté boutique
                # (cumul des cadeaux d'ouverture sur un même panier).
                raise InvalidOperation(
                    "Un seul bon cadeau événementiel autorisé par transaction"
                )
            if client_id is None:
                raise InvalidOperation(
                    "Un bon cadeau nécessite une cliente sélectionnée"
                )
            from app.services.coupon import (
                CouponError,
                redeem_coupon,
                validate_coupon,
            )

            # Per-unit (post-remise) price + libellé, pour les bons « article
            # offert » (free_item) qui couvrent la pièce éligible la moins chère.
            cart_items = [
                {
                    "price": float(
                        (up * (Decimal("100") - Decimal(str(disc))) / Decimal("100"))
                        .quantize(Decimal("0.01"))
                    ),
                    "text": (
                        f"{(prod.name if prod else (perm.name if perm else nm)) or ''} "
                        f"{(prod.category.name if prod and prod.category else '')}"
                    ),
                }
                for prod, perm, _qty, up, disc, nm, _promo, _lt in line_rows
            ]
            for amount, code in voucher_tenders:
                if not code:
                    raise InvalidOperation("Bon cadeau : code manquant")
                try:
                    preview = await validate_coupon(
                        self.db,
                        code=code,
                        cart_total=float(total_ttc),
                        client_id=client_id,
                        cart_items=cart_items,
                    )
                except CouponError as exc:
                    raise InvalidOperation(f"Bon cadeau refusé ({exc})")
                if float(amount) > preview.discount_amount + 0.01:
                    raise InvalidOperation(
                        f"Bon {code} : montant affecté ({amount} €) supérieur à "
                        f"sa valeur ({preview.discount_amount} €)"
                    )
                await redeem_coupon(self.db, preview.coupon_id, transaction.id)

        # Avoir checkout: validate balance, debit client and write ledger.
        if avoir_total > 0:
            if client_id is None:
                raise InvalidOperation("Avoir payment requires a client to be selected")
            client_result = await self.db.execute(
                select(Client).where(Client.id == client_id)
            )
            client = client_result.scalar_one_or_none()
            if client is None:
                raise ResourceNotFound("Client", client_id)
            current_balance = Decimal(str(client.avoir_credit or 0))
            if avoir_total > current_balance:
                raise InsufficientBalance(
                    f"Avoir: requested {avoir_total}, available {current_balance}"
                )
            client.avoir_credit = float(current_balance - avoir_total)
            self.db.add(
                AvoirTransaction(
                    client_id=client.id,
                    transaction_id=transaction.id,
                    tx_type=AvoirTxType.debit,
                    amount=float(avoir_total),
                    reason=f"Sale #{transaction.transaction_number}",
                )
            )

        await self.db.flush()
        await self.db.refresh(transaction)
        return transaction

    async def list_transactions(
        self, skip: int = 0, limit: int = 50
    ) -> list[dict]:
        """Return a paginated list of transactions."""
        result = await self.db.execute(
            select(Transaction)
            .order_by(Transaction.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        transactions = result.scalars().all()
        return [
            {
                "id": str(t.id),
                "transaction_number": t.transaction_number,
                "transaction_type": t.transaction_type.value,
                "total_ttc": float(t.total_ttc),
                "total_ht": float(t.total_ht),
                "total_tva": float(t.total_tva),
                "created_at": t.created_at.isoformat() if t.created_at else None,
                "item_count": len(t.items) if t.items else 0,
            }
            for t in transactions
        ]

    async def get_transaction(self, transaction_id: uuid.UUID) -> dict | None:
        """Return a single transaction with items, payments, and client info."""
        from app.models.client import Client
        result = await self.db.execute(
            select(Transaction).where(Transaction.id == transaction_id)
        )
        t = result.scalar_one_or_none()
        if t is None:
            return None

        # Build product name map for items that have a product_id
        product_ids = [item.product_id for item in (t.items or []) if item.product_id]
        product_names: dict[str, str] = {}
        if product_ids:
            prod_result = await self.db.execute(
                select(Product.id, Product.name).where(Product.id.in_(product_ids))
            )
            for pid, pname in prod_result.all():
                product_names[str(pid)] = pname

        # Load client if present
        client_data = None
        if t.client_id:
            c_result = await self.db.execute(
                select(Client).where(Client.id == t.client_id)
            )
            client = c_result.scalar_one_or_none()
            if client:
                client_data = {
                    "id": str(client.id),
                    "first_name": client.first_name,
                    "last_name": client.last_name,
                    "email": client.email,
                    "phone": client.phone,
                }

        return {
            "id": str(t.id),
            "transaction_number": t.transaction_number,
            "type": t.transaction_type.value,
            "total_ttc": float(t.total_ttc),
            "total_ht": float(t.total_ht),
            "tax_amount": float(t.total_tva),
            "hash_chain": t.hash_chain,
            "cashier_id": str(t.cashier_id) if t.cashier_id else None,
            "created_at": t.created_at.isoformat() if t.created_at else None,
            "client": client_data,
            "items": [
                {
                    "id": str(item.id),
                    "product_id": str(item.product_id) if item.product_id else None,
                    "name": (
                        getattr(item, "product_name", None)
                        or (product_names.get(str(item.product_id)) if item.product_id else None)
                        or "Article"
                    ),
                    "quantity": item.quantity,
                    "unit_price": float(item.unit_price),
                    "discount_percent": float(item.discount_percent),
                    "line_total": float(item.line_total),
                }
                for item in (t.items or [])
            ],
            "payments": [
                {
                    "id": str(p.id),
                    "method": p.method.value,
                    "amount": float(p.amount),
                }
                for p in (t.payments or [])
            ],
        }

    # ------------------------------------------------------------------
    # Cash Drawer
    # ------------------------------------------------------------------

    async def open_drawer(
        self,
        user_id: uuid.UUID,
        opening_amount: Decimal,
        cashier_id: uuid.UUID | None = None,
        opening_breakdown: list[dict] | None = None,
    ) -> CashDrawer:
        """Open a new cash drawer. Raises if one is already open.

        ``opening_breakdown`` is the optional itemised count
        ``[{"denom": 50, "count": 5}, {"denom": 20, "count": 10}, ...]`` —
        rendered on the Z report and printed at closing to help the cashier
        reconcile any discrepancy.
        """
        existing = await self.get_open_drawer()
        if existing:
            raise InvalidOperation("A cash drawer is already open")
        drawer = CashDrawer(
            user_id=user_id,
            cashier_id=cashier_id,
            opened_at=datetime.now(timezone.utc),
            opening_amount=float(opening_amount),
            opening_breakdown=opening_breakdown,
            is_open=True,
        )
        self.db.add(drawer)
        await self.db.flush()
        await self.db.refresh(drawer)
        return drawer

    async def close_drawer(
        self,
        user_id: uuid.UUID,
        closing_amount: Decimal,
        cashier_id: uuid.UUID | None = None,
        closing_breakdown: list[dict] | None = None,
        closing_note: str | None = None,
        allowed_discrepancy_override: Decimal | None = None,
    ) -> CashDrawer:
        """Close the currently open drawer.

        The expected amount now includes cash payments PLUS the running
        balance of cash movements (deposits / withdrawals during the day),
        not just the opening float — otherwise a bank deposit looks like a
        discrepancy at closing.

        ``closing_breakdown`` mirrors ``opening_breakdown`` and is rendered on
        the Z report. ``closing_note`` is mandatory client-side when the
        discrepancy exceeds ``allowed_discrepancy``; the API accepts whatever
        the UI sends but the Z report flags the case in red.
        ``allowed_discrepancy_override`` lets a manager raise the per-drawer
        threshold without touching global settings.
        """
        from app.models.cash_movement import CashMovement, CashMovementDirection

        drawer = await self.get_open_drawer()
        if not drawer:
            raise ResourceNotFound("CashDrawer")
        if cashier_id is not None:
            drawer.cashier_id = cashier_id

        # Use a small tolerance window when comparing drawer.opened_at to
        # transaction timestamps. SQLite's TEXT-based DateTime storage can
        # serialize the drawer's timezone-aware ``datetime.now(timezone.utc)``
        # with microseconds while ``func.now()`` (transactions) produces a
        # second-precision string — straight ``>=`` would then exclude sales
        # recorded in the same wall-clock second as the open call.
        period_start = drawer.opened_at - timedelta(seconds=1)

        # Sum cash payments during the drawer period
        cash_sum_result = await self.db.execute(
            select(func.coalesce(func.sum(Payment.amount), 0))
            .join(Transaction, Payment.transaction_id == Transaction.id)
            .where(
                Payment.method == PaymentMethod.cash,
                Transaction.created_at >= period_start,
            )
        )
        cash_total = Decimal(str(cash_sum_result.scalar_one()))

        # Net cash refunds during the drawer period subtract from the till
        refund_sum_result = await self.db.execute(
            select(func.coalesce(func.sum(Payment.amount), 0))
            .join(Transaction, Payment.transaction_id == Transaction.id)
            .where(
                Payment.method == PaymentMethod.cash,
                Transaction.created_at >= period_start,
                Transaction.transaction_type == TransactionType.refund,
            )
        )
        cash_refund_total = Decimal(str(refund_sum_result.scalar_one()))

        # Cash movements (deposits in / withdrawals out) during the day
        in_sum = await self.db.execute(
            select(func.coalesce(func.sum(CashMovement.amount), 0))
            .where(
                CashMovement.drawer_id == drawer.id,
                CashMovement.direction == CashMovementDirection.inflow,
            )
        )
        out_sum = await self.db.execute(
            select(func.coalesce(func.sum(CashMovement.amount), 0))
            .where(
                CashMovement.drawer_id == drawer.id,
                CashMovement.direction == CashMovementDirection.outflow,
            )
        )
        cash_in = Decimal(str(in_sum.scalar_one()))
        cash_out = Decimal(str(out_sum.scalar_one()))

        drawer.closing_amount = float(closing_amount)
        drawer.expected_amount = float(
            Decimal(str(drawer.opening_amount))
            + cash_total
            - cash_refund_total
            + cash_in
            - cash_out
        )
        drawer.closing_breakdown = closing_breakdown
        drawer.closing_note = closing_note
        if allowed_discrepancy_override is not None:
            drawer.allowed_discrepancy = float(allowed_discrepancy_override)
        drawer.closed_at = datetime.now(timezone.utc)
        drawer.is_open = False

        await self.db.flush()
        await self.db.refresh(drawer)
        return drawer

    async def get_open_drawer(self) -> CashDrawer | None:
        """Return the currently open cash drawer, or None."""
        result = await self.db.execute(
            select(CashDrawer).where(CashDrawer.is_open.is_(True)).limit(1)
        )
        return result.scalar_one_or_none()

    async def finalize_sale(
        self,
        transaction: Transaction,
        *,
        coupon_code: str | None,
        user_id: uuid.UUID,
    ) -> None:
        """Post-sign finalization: coupon redemption + loyalty + analytics events.

        Called from the router after FiscalService.sign_transaction(). Failures in
        any step are logged and swallowed — they never roll back the signed sale.
        """
        # Coupon redemption
        if coupon_code:
            from app.services.coupon import CouponError, redeem_coupon, validate_coupon
            try:
                preview = await validate_coupon(
                    self.db,
                    code=coupon_code,
                    cart_total=float(transaction.total_ttc),
                    client_id=transaction.client_id,
                )
                await redeem_coupon(self.db, preview.coupon_id, transaction.id)
            except CouponError as exc:
                logger.warning(
                    "Coupon redemption failed for tx=%s code=%s reason=%s",
                    transaction.id, coupon_code, exc,
                )

        # Loyalty: 1 € = 1 pt; every 100 pts crossed → 5 € gift cheque (auto,
        # no expiry by default — all values admin-configurable).
        if transaction.client_id is not None:
            try:
                await self._credit_loyalty_and_emit_milestones(transaction)
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "Loyalty milestone hook failed for tx=%s: %s",
                    transaction.id, exc,
                )

        # Emit analytics events (P1-003)
        from app.models.events import EventSource, EventType
        from app.services.events import EventService
        events = EventService(self.db)
        if transaction.client_id is not None:
            await events.emit(
                EventType.customer_visited,
                source=EventSource.pos,
                customer_id=transaction.client_id,
                transaction_id=transaction.id,
                user_id=user_id,
            )
        for item in (transaction.items or []):
            if item.product_id is None:
                continue
            await events.emit(
                EventType.product_sold,
                source=EventSource.pos,
                customer_id=transaction.client_id,
                product_id=item.product_id,
                transaction_id=transaction.id,
                user_id=user_id,
                meta={
                    "quantity": int(item.quantity),
                    "unit_price": float(item.unit_price),
                    "discount_percent": float(item.discount_percent or 0),
                },
            )

    # ------------------------------------------------------------------
    # Loyalty (1 € = 1 pt, 100 pts = chèque cadeau 5 € auto)
    # ------------------------------------------------------------------

    async def _credit_loyalty_and_emit_milestones(
        self, transaction: Transaction
    ) -> None:
        """Credit points + emit milestone coupons.

        Only invoked when the sale has a client. Loads/creates the
        ``LoyaltyAccount`` lazily so unenrolled clients still earn points
        from the moment they share their email.
        """
        from app.models.client import (
            LoyaltyAccount,
            LoyaltyTransaction,
            LoyaltyTxType,
        )
        from app.models.coupon import Coupon, CouponDiscountType, CouponSource
        from app.services.coupon import _draw_unique_code  # collision-safe helper
        from app.services.loyalty_config import get_earning_config
        from app.services.offers_engine import (
            milestones_crossed,
            points_to_credit,
        )

        cfg = await get_earning_config(self.db)
        # Les articles en promotion / opération (Solde, markdown) ne cotisent
        # PAS de points de fidélité : on ne crédite que sur les lignes non
        # promotionnelles. Repli sur total_ttc si la vente n'a pas d'items
        # chargés (compat anciens appels / seeds).
        items = list(transaction.items or [])
        if items:
            eligible_amount = sum(
                float(item.line_total or 0)
                for item in items
                if not getattr(item, "promotional", False)
            )
        else:
            eligible_amount = float(transaction.total_ttc or 0)
        points = points_to_credit(eligible_amount, cfg.euro_per_point)
        if points <= 0:
            return

        result = await self.db.execute(
            select(LoyaltyAccount).where(
                LoyaltyAccount.client_id == transaction.client_id
            )
        )
        account = result.scalar_one_or_none()
        if account is None:
            from app.services.membership_id import generate_membership_number

            membership = await generate_membership_number(self.db)
            account = LoyaltyAccount(
                client_id=transaction.client_id,
                points=0,
                membership_number=membership,
            )
            self.db.add(account)
            await self.db.flush()

        # Idempotency guard: a replay (e.g. router crash between flush and
        # commit on the first attempt) must NOT credit the same sale twice.
        # The earn ledger row is keyed by the unique transaction_number.
        sale_marker = f"Sale #{transaction.transaction_number}"
        already = await self.db.execute(
            select(LoyaltyTransaction.id).where(
                LoyaltyTransaction.account_id == account.id,
                LoyaltyTransaction.tx_type == LoyaltyTxType.earn,
                LoyaltyTransaction.description == sale_marker,
            ).limit(1)
        )
        if already.scalar_one_or_none() is not None:
            return

        before = int(account.points or 0)
        account.points = before + points
        self.db.add(LoyaltyTransaction(
            account_id=account.id,
            tx_type=LoyaltyTxType.earn,
            points=points,
            description=sale_marker,
        ))

        crossed = milestones_crossed(before, account.points, cfg.voucher_threshold)
        if crossed <= 0:
            return

        now = datetime.now(timezone.utc)
        # voucher_valid_days == 0 → chèque cadeau SANS expiration (valid_until
        # NULL). Une valeur > 0 réintroduit une date limite.
        valid_until = (
            now + timedelta(days=cfg.voucher_valid_days)
            if cfg.voucher_valid_days > 0 else None
        )
        voucher_value = cfg.voucher_value_cents / 100.0
        created_codes: list[str] = []
        for _ in range(crossed):
            code = await _draw_unique_code(self.db, "LOYAL")
            self.db.add(Coupon(
                code=code,
                client_id=transaction.client_id,
                discount_type=CouponDiscountType.amount,
                discount_value=voucher_value,
                source=CouponSource.loyalty_milestone,
                valid_from=now,
                valid_until=valid_until,
                is_active=True,
                notes=(
                    f"Chèque cadeau fidélité {voucher_value:g} € — palier "
                    f"{cfg.voucher_threshold} pts (tx #{transaction.transaction_number})"
                ),
            ))
            created_codes.append(code)

        # Notification cliente : un chèque cadeau vient d'être généré. Best-effort
        # (email + SMS si opt-in) — n'échoue jamais la vente.
        await self.db.flush()
        for code in created_codes:
            try:
                await self._notify_loyalty_voucher(
                    transaction.client_id, code, voucher_value, valid_until
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "Loyalty voucher notification failed for tx=%s code=%s: %s",
                    transaction.id, code, exc,
                )

    async def _notify_loyalty_voucher(
        self,
        client_id: uuid.UUID,
        code: str,
        value_eur: float,
        valid_until: datetime | None,
    ) -> None:
        """Prévient la cliente qu'un chèque cadeau fidélité a été généré.

        Information contractuelle (mouvement de cagnotte) → envoyée même sans
        opt-in marketing ; seul l'absence de contact (email/téléphone) arrête.
        Email prioritaire (template ``loyalty_voucher``, éditable), SMS si la
        cliente n'a pas d'email mais un téléphone.
        """
        from app.models.client import Client
        from app.services.communications import log_communication, render_template

        client = (
            await self.db.execute(select(Client).where(Client.id == client_id))
        ).scalar_one_or_none()
        if client is None:
            return

        # valid_until NULL = chèque cadeau sans expiration.
        valide_jusqu_au = (
            f"jusqu'au {valid_until.date().strftime('%d/%m/%Y')}"
            if valid_until else "sans date d'expiration"
        )
        prenom = (client.first_name or "").strip() or "Bonjour"
        context = {
            "prenom": prenom,
            "valeur": f"{value_eur:g}",
            "code_bon": code,
            "valide_jusqu_au": valide_jusqu_au,
        }

        if client.email:
            from app.services.email_gateway import (
                EmailDeliveryError,
                EmailMessage,
                send_email,
            )

            rendered = await render_template(
                self.db,
                "loyalty_voucher",
                context,
                fallback_subject="🎁 Vintiz — votre chèque cadeau fidélité de {valeur} €",
                fallback_html=(
                    "<p>Bonjour {prenom},</p>"
                    "<p>Félicitations ! Vous avez atteint 100 points de fidélité. "
                    "Un <strong>chèque cadeau de {valeur} €</strong> (code "
                    "<strong>{code_bon}</strong>) vient d'être crédité sur votre "
                    "compte. Valable {valide_jusqu_au}, à présenter en "
                    "caisse lors de votre prochain passage.</p>"
                ),
                fallback_text=(
                    "Bonjour {prenom}, vous avez atteint 100 points : un chèque "
                    "cadeau de {valeur} € (code {code_bon}) a été crédité sur votre "
                    "compte. Valable {valide_jusqu_au}."
                ),
            )
            status = "sent"
            backend = "simulation"
            try:
                outcome = send_email(EmailMessage(
                    to=client.email,
                    to_name=client.first_name or None,
                    subject=rendered.subject or "Vintiz — votre chèque cadeau fidélité",
                    html=rendered.html or "",
                    text=rendered.text or "",
                    tags=["loyalty-voucher"],
                ))
                status = outcome.status
                backend = outcome.backend
            except EmailDeliveryError as exc:
                status = "failed"
                backend = "error"
                logger.warning("loyalty_voucher email failed for %s: %s", client.email, exc)
            await log_communication(
                self.db,
                client_id=client.id,
                channel="email",
                kind="loyalty_voucher",
                status=status,
                to_address=client.email,
                subject=rendered.subject,
                backend=backend,
                template_key=rendered.template_key,
            )
        elif client.phone:
            from app.services.sms_gateway import SMSMessage, send_sms

            body = (
                f"Vintiz : bravo {prenom} ! 100 pts atteints. Cheque cadeau de "
                f"{value_eur:g} EUR (code {code}) credite sur votre compte, "
                f"valable {valide_jusqu_au}."
            )
            outcome = send_sms(SMSMessage(to=client.phone, body=body))
            await log_communication(
                self.db,
                client_id=client.id,
                channel="sms",
                kind="loyalty_voucher",
                status=getattr(outcome, "status", "sent"),
                to_address=client.phone,
                subject=None,
                backend=getattr(outcome, "backend", "simulation"),
            )
