"""SATO CT4-LX label printer driver (SBPL protocol).

The CT4-LX accepts native SATO SBPL commands. To print the rendered PNG
label generated by :func:`app.services.label.generate_label` we convert it
to a monochrome bitmap and embed it inside an SBPL ``GM`` graphics command.

Everything is sent raw to TCP port 9100.
"""

from __future__ import annotations

import io
import socket
from datetime import datetime
from typing import Any

try:
    from PIL import Image
except ImportError:  # pragma: no cover - Pillow already a project dep
    Image = None  # type: ignore[assignment]

STX = b"\x02"
ETX = b"\x03"
ESC = b"\x1b"


def _png_to_sbpl_graphics(
    png_bytes: bytes,
    *,
    target_width_dots: int = 400,
    target_height_dots: int = 240,
) -> tuple[bytes, int, int, int]:
    """Convert a PNG to a monochrome bitmap wrapped in SBPL ``GM`` data.

    SBPL ``GM`` format: ``<ESC>GM<nnnnn>,<data>`` where ``nnnnn`` is the
    byte count of the raw monochrome bitmap data and ``data`` is a packed
    row-major 1-bit bitmap (MSB first, each row padded to a whole byte).
    """
    if Image is None:
        raise RuntimeError("Pillow est requis pour l'impression SATO")

    img = Image.open(io.BytesIO(png_bytes)).convert("L")
    # Resize while keeping aspect ratio within target box
    img.thumbnail((target_width_dots, target_height_dots), Image.LANCZOS)
    # Binarise at 50% gray — works well for the Vintiz label look
    mono = img.point(lambda p: 0 if p < 160 else 255, mode="1")

    width, height = mono.size
    row_bytes = (width + 7) // 8
    raw = bytearray()
    pixels = mono.load()
    for y in range(height):
        byte = 0
        bit = 7
        row = bytearray()
        for x in range(width):
            # In mode "1", 0 = black, 255 = white; SBPL wants 1 = black
            if pixels[x, y] == 0:
                byte |= 1 << bit
            bit -= 1
            if bit < 0:
                row.append(byte)
                byte = 0
                bit = 7
        if bit != 7:
            row.append(byte)
        while len(row) < row_bytes:
            row.append(0)
        raw.extend(row)

    header = f"{ESC.decode('latin-1')}GM{len(raw):05d},".encode("latin-1")
    return header + bytes(raw), width, height, row_bytes


def build_label_sbpl(
    png_bytes: bytes,
    *,
    print_speed: int = 4,
    print_darkness: str = "B",
    quantity: int = 1,
    label_width_dots: int = 400,
    label_height_dots: int = 240,
) -> bytes:
    """Wrap a PNG label inside a complete SBPL job for the CT4-LX."""
    graphics, _w, _h, _rb = _png_to_sbpl_graphics(
        png_bytes,
        target_width_dots=label_width_dots,
        target_height_dots=label_height_dots,
    )

    out = bytearray()
    out += STX + ESC + b"A"                            # start of job
    out += ESC + f"CS{print_speed}".encode("ascii")    # print speed (ips)
    out += ESC + f"#{print_darkness}".encode("ascii")  # darkness
    out += ESC + f"A1{label_height_dots:04d}{label_width_dots:04d}".encode("ascii")
    out += ESC + b"V0020"                              # vertical origin
    out += ESC + b"H0020"                              # horizontal origin
    out += graphics
    out += ESC + f"Q{quantity:04d}".encode("ascii")    # number of copies
    out += ESC + b"Z" + ETX                            # end of job
    return bytes(out)


def build_test_label() -> bytes:
    """Small SBPL test label (text only, no graphics) for diagnostics."""
    out = bytearray()
    out += STX + ESC + b"A"
    out += ESC + b"CS4"
    out += ESC + b"#B"
    out += ESC + b"A10240400"
    out += ESC + b"V0020" + ESC + b"H0020"
    out += ESC + b"L0202"  # text scale
    out += ESC + b"P1"     # font
    out += ESC + b"V0030" + ESC + b"H0030" + b"VINTIZ"
    out += ESC + b"V0080" + ESC + b"H0030" + b"Test SATO CT4-LX"
    out += ESC + b"V0130" + ESC + b"H0030" + datetime.now().strftime("%d/%m/%Y %H:%M").encode("ascii")
    out += ESC + b"Q0001"
    out += ESC + b"Z" + ETX
    return bytes(out)


def send_raw(host: str, port: int, payload: bytes, timeout: float = 10.0) -> None:
    if not host:
        raise ValueError("Imprimante SATO non configuree : adresse IP manquante")
    with socket.create_connection((host, int(port)), timeout=timeout) as sock:
        sock.sendall(payload)


def print_label(png_bytes: bytes, host: str, port: int = 9100, *, quantity: int = 1) -> int:
    payload = build_label_sbpl(png_bytes, quantity=quantity)
    send_raw(host, port, payload)
    return len(payload)


def print_test(host: str, port: int = 9100) -> None:
    send_raw(host, port, build_test_label())
