import logging
import uuid
from decimal import Decimal

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.database import get_db
from app.core.security import RoleChecker, get_current_user
from app.models.user import User
from app.schemas.user import (
    CashierPinClearRequest,
    CashierPinLoginRequest,
    CashierPinSetRequest,
    CashierResponse,
    CashierWithPinStatusResponse,
)
from app.services.cashier import CashierService
from app.services.events import EventService
from app.services.fiscal import FiscalService
from app.services.pos import PosService
from app.services.refund import RefundLineInput, RefundService

manager_only = RoleChecker(["manager"])

logger = logging.getLogger("vintiz")

router = APIRouter(prefix="/pos", tags=["pos"])


class CartItem(BaseModel):
    product_id: uuid.UUID | None = None
    name: str | None = None
    quantity: int = 1
    unit_price: float | None = None
    discount_percent: float = 0


class PaymentInput(BaseModel):
    method: str  # cash, card, cheque
    amount: Decimal


class CreateTransactionRequest(BaseModel):
    items: list[CartItem]
    payments: list[PaymentInput]
    client_id: uuid.UUID | None = None
    cashier_id: uuid.UUID | None = None
    # Idempotence key generated by the POS UI (P1-005). When supplied,
    # a duplicate POST returns the original transaction.
    client_uuid: uuid.UUID | None = None
    # Optional coupon code to redeem atomically with the sale (P4-008).
    coupon_code: str | None = None


class ValidateCouponRequest(BaseModel):
    code: str
    cart_total: float
    client_id: uuid.UUID | None = None


class OpenDrawerRequest(BaseModel):
    opening_amount: Decimal
    cashier_id: uuid.UUID | None = None


class CloseDrawerRequest(BaseModel):
    closing_amount: Decimal
    cashier_id: uuid.UUID | None = None


@router.post("/transactions")
async def create_transaction(
    request: CreateTransactionRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new sale transaction with payments."""
    pos_service = PosService(db)
    fiscal_service = FiscalService(db)

    transaction = await pos_service.create_transaction(
        user_id=current_user.id,
        items=request.items,
        payments=request.payments,
        client_id=request.client_id,
        cashier_id=request.cashier_id,
        client_uuid=request.client_uuid,
    )

    # If create_transaction returned the existing row (idempotent replay
    # via client_uuid), the hash chain is already set and the analytics
    # events were emitted on the first call. Skip both.
    is_replay = (
        request.client_uuid is not None
        and transaction.hash_chain
    )
    if is_replay:
        return {
            "id": str(transaction.id),
            "transaction_id": str(transaction.id),
            "transaction_number": transaction.transaction_number,
            "total_ttc": float(transaction.total_ttc),
            "replayed": True,
        }

    # Generate fiscal hash chain
    await fiscal_service.sign_transaction(transaction)

    # Coupon redemption + analytics events
    await pos_service.finalize_sale(
        transaction,
        coupon_code=request.coupon_code,
        user_id=current_user.id,
    )

    return {
        "id": str(transaction.id),
        "transaction_id": str(transaction.id),
        "transaction_number": transaction.transaction_number,
        "total_ttc": float(transaction.total_ttc),
    }


_COUPON_ERROR_MESSAGES = {
    "not_found": "Code inconnu.",
    "inactive": "Ce code a été désactivé.",
    "redeemed": "Ce code a déjà été utilisé.",
    "expired": "Ce code est expiré.",
    "not_yet_valid": "Ce code n'est pas encore valable.",
    "no_client": "Ce code est nominatif — sélectionne d'abord la cliente.",
    "wrong_client": "Ce code appartient à une autre cliente.",
}


@router.post("/coupons/validate")
async def validate_pos_coupon(
    payload: ValidateCouponRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Read-only check for the cashier preview before validation."""
    from app.services.coupon import CouponError, validate_coupon

    try:
        preview = await validate_coupon(
            db,
            code=payload.code,
            cart_total=payload.cart_total,
            client_id=payload.client_id,
        )
    except CouponError as exc:
        msg = _COUPON_ERROR_MESSAGES.get(str(exc), "Code refusé.")
        raise HTTPException(status_code=409, detail=msg)

    return {
        "code": preview.code,
        "discount_type": preview.discount_type,
        "discount_value": preview.discount_value,
        "discount_amount": preview.discount_amount,
        "new_total": preview.new_total,
        "source": preview.source,
        "valid_until": preview.valid_until.isoformat(),
    }


@router.get("/transactions")
async def list_transactions(
    skip: int = 0,
    limit: int = 50,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List recent transactions."""
    pos_service = PosService(db)
    transactions = await pos_service.list_transactions(skip=skip, limit=limit)
    return transactions


@router.get("/transactions/{transaction_id}")
async def get_transaction(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get transaction details."""
    pos_service = PosService(db)
    transaction = await pos_service.get_transaction(transaction_id)
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction not found")
    return transaction


@router.post("/drawer/open")
async def open_drawer(
    request: OpenDrawerRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Open cash drawer for the day."""
    pos_service = PosService(db)
    drawer = await pos_service.open_drawer(
        current_user.id, request.opening_amount, cashier_id=request.cashier_id
    )

    from app.models.events import EventSource, EventType
    await EventService(db).emit(
        EventType.cashier_session_opened,
        source=EventSource.pos,
        user_id=current_user.id,
        meta={
            "drawer_id": str(drawer.id),
            "cashier_id": str(request.cashier_id) if request.cashier_id else None,
            "opening_amount": float(drawer.opening_amount),
        },
    )

    return {
        "drawer_id": str(drawer.id),
        "opening_amount": float(drawer.opening_amount),
    }


@router.post("/drawer/close")
async def close_drawer(
    request: CloseDrawerRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Close cash drawer and generate Z report."""
    pos_service = PosService(db)
    fiscal_service = FiscalService(db)

    drawer = await pos_service.close_drawer(
        current_user.id, request.closing_amount, cashier_id=request.cashier_id
    )
    z_report = await fiscal_service.generate_z_report(
        drawer, current_user.id, cashier_id=request.cashier_id
    )

    from app.models.events import EventSource, EventType
    discrepancy = (
        float(drawer.closing_amount) - float(drawer.expected_amount)
        if drawer.expected_amount is not None and drawer.closing_amount is not None
        else None
    )
    await EventService(db).emit(
        EventType.cashier_session_closed,
        source=EventSource.pos,
        user_id=current_user.id,
        meta={
            "drawer_id": str(drawer.id),
            "cashier_id": str(drawer.cashier_id) if drawer.cashier_id else None,
            "z_report_number": z_report.report_number,
            "discrepancy": discrepancy,
            "transaction_count": z_report.transaction_count,
        },
    )

    return {
        "drawer_id": str(drawer.id),
        "z_report_number": z_report.report_number,
        "total_sales": float(z_report.total_sales),
        "total_refunds": float(z_report.total_refunds),
        "total_net": float(z_report.total_net),
        "transaction_count": z_report.transaction_count,
        "difference": float(drawer.closing_amount - drawer.expected_amount)
        if drawer.expected_amount
        else 0,
    }


@router.get("/drawer/current")
async def get_current_drawer(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get the currently open drawer."""
    pos_service = PosService(db)
    drawer = await pos_service.get_open_drawer()
    if not drawer:
        return {"open": False}
    return {
        "open": True,
        "drawer_id": str(drawer.id),
        "opening_amount": float(drawer.opening_amount),
    }


@router.get("/z-reports")
async def list_z_reports(
    skip: int = 0,
    limit: int = 30,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List Z reports."""
    fiscal_service = FiscalService(db)
    reports = await fiscal_service.list_z_reports(skip=skip, limit=limit)
    return reports


class CBInitiateRequest(BaseModel):
    amount: float
    description: str = "Vente Vintiz"


class ResendRequest(BaseModel):
    channel: str  # 'email' or 'sms'


# ---------------------------------------------------------------------------
# CB / SumUp endpoints
# ---------------------------------------------------------------------------

@router.post("/payments/cb/initiate")
async def initiate_cb_payment(
    request: CBInitiateRequest,
    current_user: User = Depends(get_current_user),
):
    """Initiate a SumUp card checkout. Returns checkout_id for polling."""
    from app.services.sumup_service import SumUpService
    svc = SumUpService()
    result = await svc.create_checkout(
        amount=request.amount,
        description=request.description,
    )
    return result


@router.get("/payments/cb/{checkout_id}/status")
async def get_cb_payment_status(
    checkout_id: str,
    current_user: User = Depends(get_current_user),
):
    """Poll the status of a SumUp checkout."""
    from app.services.sumup_service import SumUpService
    svc = SumUpService()
    result = await svc.get_checkout_status(checkout_id)
    return result


@router.delete("/payments/cb/{checkout_id}")
async def cancel_cb_payment(
    checkout_id: str,
    current_user: User = Depends(get_current_user),
):
    """Cancel a pending SumUp checkout."""
    from app.services.sumup_service import SumUpService
    svc = SumUpService()
    ok = await svc.cancel_checkout(checkout_id)
    return {"cancelled": ok}


# ---------------------------------------------------------------------------
# SumUp sandbox admin endpoints
# ---------------------------------------------------------------------------

@router.get("/payments/cb/sandbox/config")
async def get_sumup_sandbox_config(current_user: User = Depends(get_current_user)):
    """Return the current SumUp configuration (environment, keys set, etc.)."""
    from app.services.sumup_service import SumUpService
    return SumUpService().describe()


@router.get("/payments/cb/sandbox/state")
async def get_sumup_sandbox_state(
    limit: int = 50,
    current_user: User = Depends(get_current_user),
):
    """Return a snapshot of sandbox checkouts and event log for live debugging."""
    from app.services.sumup_service import SumUpService
    return SumUpService().sandbox_snapshot(limit=limit)


@router.post("/payments/cb/sandbox/{checkout_id}/approve")
async def approve_sumup_sandbox(
    checkout_id: str,
    current_user: User = Depends(get_current_user),
):
    """Force a pending sandbox checkout to PAID."""
    from app.services.sumup_service import SumUpService
    result = SumUpService().sandbox_approve(checkout_id)
    if not result.get("ok"):
        raise HTTPException(status_code=404, detail=result.get("error", "unknown"))
    return result


@router.post("/payments/cb/sandbox/{checkout_id}/decline")
async def decline_sumup_sandbox(
    checkout_id: str,
    current_user: User = Depends(get_current_user),
):
    """Force a pending sandbox checkout to FAILED."""
    from app.services.sumup_service import SumUpService
    result = SumUpService().sandbox_decline(checkout_id)
    if not result.get("ok"):
        raise HTTPException(status_code=404, detail=result.get("error", "unknown"))
    return result


@router.post("/payments/cb/sandbox/clear")
async def clear_sumup_sandbox(current_user: User = Depends(get_current_user)):
    """Clear the sandbox event log and checkout store."""
    from app.services.sumup_service import SumUpService
    SumUpService().sandbox_clear()
    return {"ok": True}


class SandboxTestRequest(BaseModel):
    amount: float = 12.50
    description: str = "Test sandbox Vintiz"


@router.post("/payments/cb/sandbox/test")
async def test_sumup_sandbox(
    request: SandboxTestRequest,
    current_user: User = Depends(get_current_user),
):
    """Create a test checkout in sandbox — useful for the admin UI button."""
    from app.services.sumup_service import SumUpService
    svc = SumUpService()
    return await svc.create_checkout(
        amount=request.amount,
        description=request.description,
    )


@router.post("/transactions/{transaction_id}/resend")
async def resend_transaction(
    transaction_id: uuid.UUID,
    request: ResendRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Resend a transaction receipt by email or SMS."""
    pos_service = PosService(db)
    transaction = await pos_service.get_transaction(transaction_id)
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction introuvable")

    client = transaction.get("client")
    if not client:
        raise HTTPException(status_code=400, detail="Aucun client associe a cette transaction")

    ticket_num = transaction["transaction_number"]
    total = transaction["total_ttc"]
    items_text = "\n".join(
        f"  - {item['name']} x{item['quantity']} : {item['unit_price']:.2f} EUR"
        for item in transaction.get("items", [])
    )

    if request.channel == "email":
        if not client.get("email"):
            raise HTTPException(status_code=400, detail="Ce client n'a pas d'adresse email")
        from app.services.email_gateway import (
            EmailDeliveryError,
            EmailMessage,
            send_email as _gateway_send,
        )

        body_text = (
            f"Bonjour {client['first_name']},\n\n"
            f"Voici le recu de votre achat chez Vintiz.\n\n"
            f"Ticket #{ticket_num}\n"
            f"Articles :\n{items_text}\n\n"
            f"Total TTC : {total:.2f} EUR\n\n"
            f"Merci de votre visite !\nVintiz — Boutique de seconde main premium"
        )
        body_html = "<pre style=\"font-family: monospace\">" + body_text + "</pre>"

        try:
            outcome = _gateway_send(EmailMessage(
                to=client["email"],
                to_name=client.get("first_name"),
                subject=f"Votre reçu Vintiz #{ticket_num}",
                html=body_html,
                text=body_text,
            ))
        except EmailDeliveryError:
            logger.exception("Failed to send receipt email for transaction %s",
                             transaction_id)
            raise HTTPException(
                status_code=502,
                detail="L'envoi de l'email a échoué. Réessayez plus tard.",
            )
        logger.info("Receipt email %s for transaction %s via %s",
                    outcome.status, transaction_id, outcome.backend)
        prefix = "" if outcome.status == "sent" else "[SIMULE] "
        return {"success": True, "message": f"{prefix}Email envoyé à {client['email']}"}

    elif request.channel == "sms":
        if not client.get("phone"):
            raise HTTPException(status_code=400, detail="Ce client n'a pas de numero de telephone")
        if settings.TWILIO_ACCOUNT_SID:
            try:
                from twilio.rest import Client as TwilioClient
                tw = TwilioClient(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
                tw.messages.create(
                    body=f"Vintiz - Ticket #{ticket_num} - Total {total:.2f}EUR. Merci !",
                    from_=settings.TWILIO_FROM,
                    to=client["phone"],
                )
                logger.info("Receipt SMS sent for transaction %s", transaction_id)
                return {"success": True, "message": f"SMS envoye au {client['phone']}"}
            except Exception:
                logger.exception("Failed to send receipt SMS for transaction %s", transaction_id)
                raise HTTPException(
                    status_code=502,
                    detail="L'envoi du SMS a échoué. Réessayez plus tard.",
                )
        else:
            logger.info("Receipt SMS simulated for transaction %s", transaction_id)
            return {"success": True, "message": f"[SIMULE] SMS envoye au {client['phone']}"}
    else:
        raise HTTPException(status_code=400, detail="Canal invalide (email ou sms)")


@router.post("/transactions/{transaction_id}/print")
async def print_transaction_receipt(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Send the receipt to the MUNBYN ESC/POS printer (TCP 9100)."""
    from sqlalchemy import select
    from sqlalchemy.orm import selectinload

    from app.models.pos import PaymentMethod, Transaction
    from app.services import escpos_service
    from app.services.hardware_config import load_config

    result = await db.execute(
        select(Transaction)
        .options(selectinload(Transaction.items), selectinload(Transaction.payments))
        .where(Transaction.id == transaction_id)
    )
    transaction = result.scalar_one_or_none()
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction introuvable")

    cfg = load_config()
    rp = cfg["receipt_printer"]
    if not rp.get("enabled"):
        raise HTTPException(status_code=400, detail="Imprimante de recus desactivee dans les parametres")
    host = rp.get("host") or ""
    port = int(rp.get("port") or 9100)
    if not host:
        raise HTTPException(status_code=400, detail="Adresse IP de l'imprimante non configuree")

    try:
        escpos_service.print_receipt(
            transaction,
            host=host,
            port=port,
            width=int(rp.get("width_chars") or 42),
            cut=bool(rp.get("cut_paper", True)),
        )
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=502, detail=f"Imprimante injoignable : {exc}") from exc

    # Auto-kick drawer if cash payment and drawer enabled
    drawer_cfg = cfg["cash_drawer"]
    if drawer_cfg.get("enabled") and drawer_cfg.get("kick_on_cash"):
        has_cash = any(
            (p.method == PaymentMethod.cash)
            for p in (transaction.payments or [])
        )
        if has_cash:
            try:
                escpos_service.kick_drawer(
                    host,
                    port,
                    pin=int(drawer_cfg.get("kick_pin") or 0),
                    on_time=int(drawer_cfg.get("on_time_ms") or 50),
                    off_time=int(drawer_cfg.get("off_time_ms") or 250),
                )
            except Exception:  # noqa: BLE001 — drawer is best effort
                pass

    return {"success": True, "transaction_id": str(transaction_id)}


@router.get("/transactions/{transaction_id}/receipt")
async def get_transaction_receipt(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate and return receipt text for a transaction."""
    from sqlalchemy import select
    from app.models.client import Client, LoyaltyTransaction, LoyaltyTxType
    from app.models.pos import Transaction
    from app.services.receipt import ReceiptService

    result = await db.execute(
        select(Transaction).where(Transaction.id == transaction_id)
    )
    transaction = result.scalar_one_or_none()
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction not found")

    # Resolve fidelity context (PR1): the footer surfaces member info or
    # a "would-have-earned" line for non-members.
    client = None
    loyalty_account = None
    points_earned = None
    if transaction.client_id is not None:
        client_row = await db.execute(
            select(Client).where(Client.id == transaction.client_id)
        )
        client = client_row.scalar_one_or_none()
        if client and client.loyalty_account is not None:
            loyalty_account = client.loyalty_account
            earn_row = await db.execute(
                select(LoyaltyTransaction.points)
                .where(
                    LoyaltyTransaction.account_id == loyalty_account.id,
                    LoyaltyTransaction.tx_type == LoyaltyTxType.earn,
                    LoyaltyTransaction.description == f"Sale #{transaction.transaction_number}",
                )
            )
            points_earned = earn_row.scalar_one_or_none() or 0

    receipt_service = ReceiptService()
    receipt_text = receipt_service.generate_receipt_text(
        transaction,
        client=client,
        loyalty_account=loyalty_account,
        points_earned_on_sale=points_earned,
    )

    return {
        "receipt_text": receipt_text,
        "transaction_id": str(transaction_id),
    }


# ---------------------------------------------------------------------------
# Cashier identification (PIN-based) — tickets P1-002 + P1-014
# ---------------------------------------------------------------------------


@router.post(
    "/cashier/set-pin",
    dependencies=[Depends(manager_only)],
)
async def set_cashier_pin(
    request: CashierPinSetRequest,
    db: AsyncSession = Depends(get_db),
):
    """Set or replace a 4-digit POS PIN for a user. Manager only."""
    result = await db.execute(select(User).where(User.id == request.user_id))
    user = result.scalar_one_or_none()
    if user is None:
        raise HTTPException(status_code=404, detail="User not found")
    cashier_service = CashierService(db)
    await cashier_service.set_pin(user, request.pin)
    return {"user_id": str(user.id), "has_pin": True}


@router.post(
    "/cashier/clear-pin",
    dependencies=[Depends(manager_only)],
)
async def clear_cashier_pin(
    request: CashierPinClearRequest,
    db: AsyncSession = Depends(get_db),
):
    """Remove a user's POS PIN. Manager only."""
    result = await db.execute(select(User).where(User.id == request.user_id))
    user = result.scalar_one_or_none()
    if user is None:
        raise HTTPException(status_code=404, detail="User not found")
    cashier_service = CashierService(db)
    await cashier_service.clear_pin(user)
    return {"user_id": str(user.id), "has_pin": False}


@router.post("/cashier/login", response_model=CashierResponse)
async def cashier_pin_login(
    request: CashierPinLoginRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Identify a cashier from their 4-digit PIN.

    Requires a valid JWT (the iPad is logged in as a manager). Returns
    the cashier's id and role so the POS UI can stamp subsequent
    transactions / drawer events.
    """
    cashier_service = CashierService(db)
    cashier = await cashier_service.authenticate_pin(request.pin)
    logger.info(
        "Cashier PIN login: cashier_id=%s by_user=%s",
        cashier.id,
        current_user.id,
    )
    return CashierResponse(
        id=cashier.id,
        username=cashier.username,
        role=cashier.role.value,
    )


@router.get(
    "/cashier/list",
    response_model=list[CashierWithPinStatusResponse],
    dependencies=[Depends(manager_only)],
)
async def list_cashiers(db: AsyncSession = Depends(get_db)):
    """List all users with their PIN status. Manager only."""
    cashier_service = CashierService(db)
    return await cashier_service.list_with_pin_status()


# ---------------------------------------------------------------------------
# Refunds (P1-010 + P1-016) — partial / full, settled in cash, card or avoir
# ---------------------------------------------------------------------------


class RefundLineRequest(BaseModel):
    transaction_item_id: uuid.UUID
    quantity: int


class RefundRequest(BaseModel):
    items: list[RefundLineRequest]
    refund_method: str  # cash | card | cheque | avoir
    cashier_id: uuid.UUID | None = None
    reason: str | None = None


@router.post("/transactions/{transaction_id}/refund")
async def refund_transaction(
    transaction_id: uuid.UUID,
    request: RefundRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Issue a partial or full refund of a sale.

    Refunded products are returned to display status. The refund total can
    be settled in cash, on card (record only — SumUp call is a TODO), or as
    store credit on the customer's avoir balance.
    """
    refund_service = RefundService(db)
    fiscal_service = FiscalService(db)

    refund_tx = await refund_service.refund_transaction(
        original_tx_id=transaction_id,
        items=[
            RefundLineInput(line.transaction_item_id, line.quantity)
            for line in request.items
        ],
        refund_method=request.refund_method,
        user_id=current_user.id,
        cashier_id=request.cashier_id,
        reason=request.reason,
    )
    await fiscal_service.sign_transaction(refund_tx)

    # Emit a product.refunded event per refunded item (P1-003).
    from app.models.events import EventSource, EventType
    events = EventService(db)
    for item in (refund_tx.items or []):
        if item.product_id is None:
            continue
        await events.emit(
            EventType.product_refunded,
            source=EventSource.pos,
            customer_id=refund_tx.client_id,
            product_id=item.product_id,
            transaction_id=refund_tx.id,
            user_id=current_user.id,
            meta={
                "quantity": int(item.quantity),
                "refund_method": request.refund_method,
                "reason": request.reason,
                "original_transaction_id": str(refund_tx.original_transaction_id),
            },
        )

    return {
        "id": str(refund_tx.id),
        "transaction_number": refund_tx.transaction_number,
        "transaction_type": refund_tx.transaction_type.value,
        "original_transaction_id": str(refund_tx.original_transaction_id)
        if refund_tx.original_transaction_id
        else None,
        "total_ttc": float(refund_tx.total_ttc),
        "refund_method": request.refund_method,
        "hash_chain": refund_tx.hash_chain,
    }


# ---------------------------------------------------------------------------
# Loyalty subscription + client identification (PR1)
# ---------------------------------------------------------------------------


class LoyaltySubscribeRequest(BaseModel):
    first_name: str
    last_name: str
    email: str
    postal_code: str | None = None
    accept_terms: bool
    optin_newsletter: bool = False
    optin_profiling: bool = False
    mode_override: str | None = None  # null = use admin config


@router.post(
    "/loyalty/subscribe",
    status_code=201,
    dependencies=[Depends(manager_only)],
)
async def subscribe_loyalty(
    request: LoyaltySubscribeRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Enrol a client in the loyalty programme from the POS.

    409 with ``existing_membership_number`` on duplicate email — the POS
    UI proposes to fuse instead of creating a second account.
    """
    if not request.accept_terms:
        raise HTTPException(status_code=400, detail="Conditions a accepter")

    from app.services.loyalty import LoyaltyDuplicateError, subscribe
    from app.services.loyalty_config import get_subscription_config

    config = await get_subscription_config(db)
    mode = request.mode_override or config.mode

    try:
        client, account = await subscribe(
            db,
            first_name=request.first_name,
            last_name=request.last_name,
            email=request.email,
            postal_code=request.postal_code,
            mode=mode,
            optin_newsletter=request.optin_newsletter,
            optin_profiling=request.optin_profiling,
            user_id=current_user.id,
        )
    except LoyaltyDuplicateError as exc:
        await db.rollback()
        raise HTTPException(
            status_code=409,
            detail={
                "code": "duplicate_email",
                "existing_membership_number": exc.membership_number,
                "client_id": str(exc.client_id),
            },
        )
    await db.commit()
    return {
        "client_id": str(client.id),
        "membership_number": account.membership_number,
        "mode_applied": mode,
        "expires_at": client.loyalty_expires_at.isoformat()
        if client.loyalty_expires_at
        else None,
    }


@router.get("/clients/{client_id}/companion")
async def pos_companion(
    client_id: uuid.UUID,
    cart_total_cents: int = 0,
    items: str | None = None,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Cart-aware up-sell payload for the POS companion panel (PR4).

    ``items`` is a comma-separated list of product UUIDs already in the
    cart. Empty cart is supported — the suggestions block is just empty.
    """
    cart_product_ids: list[uuid.UUID] = []
    if items:
        for raw in items.split(","):
            raw = raw.strip()
            if not raw:
                continue
            try:
                cart_product_ids.append(uuid.UUID(raw))
            except ValueError:
                continue

    from app.services.pos_companion import companion_payload

    try:
        payload = await companion_payload(
            db,
            client_id=client_id,
            cart_total_cents=max(0, int(cart_total_cents)),
            cart_product_ids=cart_product_ids,
        )
    except LookupError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    return payload


@router.get("/clients/identify")
async def identify_client_pos(
    q: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Resolve a client from a free-form input (membership / email / phone)."""
    from app.models.client import Client, LoyaltyAccount
    from app.services.membership_id import (
        is_membership_number,
        lookup_by_membership_number,
    )

    q = (q or "").strip()
    if not q:
        raise HTTPException(status_code=400, detail="empty query")

    client: Client | None = None
    if is_membership_number(q):
        client = await lookup_by_membership_number(db, q)
    elif "@" in q:
        row = await db.execute(select(Client).where(Client.email == q.lower()))
        client = row.scalar_one_or_none()
    else:
        row = await db.execute(select(Client).where(Client.phone == q))
        client = row.scalar_one_or_none()

    if client is None:
        raise HTTPException(status_code=404, detail="client_not_found")

    loyalty = client.loyalty_account
    return {
        "client_id": str(client.id),
        "first_name": client.first_name,
        "last_name": client.last_name,
        "email": client.email,
        "phone": client.phone,
        "membership_number": loyalty.membership_number if loyalty else None,
        "loyalty": {
            "active": loyalty is not None,
            "points": loyalty.points if loyalty else 0,
            "expires_at": client.loyalty_expires_at.isoformat()
            if client.loyalty_expires_at
            else None,
        },
    }
