import logging
import uuid
from decimal import Decimal

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.database import get_db
from app.core.security import RoleChecker, get_current_user
from app.models.audit import AuditLog
from app.models.user import User, UserRole
from app.schemas.user import (
    CashierPinClearRequest,
    CashierPinLoginRequest,
    CashierPinSetRequest,
    CashierResponse,
    CashierWithPinStatusResponse,
)
from app.services.cash_payment_validator import (
    validate as validate_cash_payments,
)
from app.services.cashier import CashierService
from app.services.events import EventService
from app.services.fiscal import FiscalService
from app.services.pos import PosService
from app.services.refund import RefundLineInput, RefundService
from app.services.sumup_service import redact_sumup_error

manager_only = RoleChecker(["manager"])

logger = logging.getLogger("vintiz")

router = APIRouter(prefix="/pos", tags=["pos"])


class CartItem(BaseModel):
    product_id: uuid.UUID | None = None
    name: str | None = None
    quantity: int = 1
    unit_price: float | None = None
    discount_percent: float = 0


class PaymentInput(BaseModel):
    method: str  # cash, card, cheque
    amount: Decimal


class CreateTransactionRequest(BaseModel):
    items: list[CartItem]
    payments: list[PaymentInput]
    client_id: uuid.UUID | None = None
    cashier_id: uuid.UUID | None = None
    # Idempotence key generated by the POS UI (P1-005). When supplied,
    # a duplicate POST returns the original transaction.
    client_uuid: uuid.UUID | None = None
    # Optional coupon code to redeem atomically with the sale (P4-008).
    coupon_code: str | None = None
    # B2B invoice mode (PR 2/6 — POS routine SumUp). When True, the API
    # assigns a separate ``invoice_number`` (FACT-{year}-{seq:06d}) and
    # snapshots the buyer block + template id on the transaction so the
    # invoice PDF reproduces the historical document byte-identical.
    is_invoice: bool = False
    client_siret: str | None = None
    client_company_name: str | None = None
    client_billing_address: str | None = None
    template_id: uuid.UUID | None = None
    # Plafond espèces (CMF art. L.112-6, décret 2015-741). 1 000 € pour
    # un résident fiscal FR, 15 000 € pour un touriste non-résident.
    # ``customer_is_tourist`` doit être attesté par un justificatif
    # d'identité étranger vérifié en boutique.
    customer_is_tourist: bool = False
    # Override manager du plafond espèces : motif obligatoire, manager
    # uniquement, tracé en audit log.
    cash_override_reason: str | None = None


class ValidateCouponRequest(BaseModel):
    code: str
    cart_total: float
    client_id: uuid.UUID | None = None


class Denomination(BaseModel):
    """One row of the denomination grid (50 € × 5 = 250 €)."""

    denom: float  # in EUR (5, 10, 20, 50, 100, 200, 500, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2)
    count: int


class OpenDrawerRequest(BaseModel):
    opening_amount: Decimal
    cashier_id: uuid.UUID | None = None
    # Optional itemised count — when provided, rendered on the Z report
    # and lets the cashier recover from a discrepancy alert at closing.
    opening_breakdown: list[Denomination] | None = None


class CloseDrawerRequest(BaseModel):
    closing_amount: Decimal
    cashier_id: uuid.UUID | None = None
    closing_breakdown: list[Denomination] | None = None
    closing_note: str | None = None
    # Per-drawer override of the global allowed discrepancy (Settings).
    allowed_discrepancy_override: Decimal | None = None


class CashMovementRequest(BaseModel):
    direction: str  # "in" or "out"
    amount: Decimal
    reason: str = "other"  # bank_deposit | supplier_payment | personal_withdrawal | float_top_up | other
    note: str | None = None
    cashier_id: uuid.UUID | None = None


class PaymentAttemptRequest(BaseModel):
    method: str  # cash | card | cheque | avoir
    amount: Decimal
    status: str  # pending | succeeded | failed | cancelled
    cashier_id: uuid.UUID | None = None
    drawer_id: uuid.UUID | None = None
    transaction_id: uuid.UUID | None = None
    sumup_checkout_id: str | None = None
    error_detail: str | None = None
    cancelled_reason: str | None = None
    attempt_id: uuid.UUID | None = None  # supplied to update an existing attempt


@router.post("/transactions")
async def create_transaction(
    request: CreateTransactionRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new sale transaction with payments."""
    pos_service = PosService(db)
    fiscal_service = FiscalService(db)

    # Plafond légal espèces (CMF art. L.112-6) — 1 000 € résident /
    # 15 000 € non-résident. Bloque par défaut, override manager possible
    # avec motif tracé en audit log.
    cash_check = validate_cash_payments(
        request.payments,
        is_tourist=request.customer_is_tourist,
    )
    if cash_check.over_cap:
        if not request.cash_override_reason:
            raise HTTPException(
                status_code=400,
                detail={
                    "code": "cash_cap_exceeded",
                    "cash_total_eur": float(cash_check.cash_total_eur),
                    "cap_eur": float(cash_check.cap_eur),
                    "is_tourist": cash_check.is_tourist,
                    "message": cash_check.reason,
                    "override_required": True,
                },
            )
        if current_user.role != UserRole.manager:
            raise HTTPException(
                status_code=403,
                detail={
                    "code": "cash_cap_override_manager_only",
                    "message": (
                        "Le dépassement du plafond espèces nécessite "
                        "l'autorisation d'un manager."
                    ),
                },
            )
        reason = request.cash_override_reason.strip()
        if len(reason) < 10:
            raise HTTPException(
                status_code=400,
                detail={
                    "code": "cash_override_reason_too_short",
                    "message": (
                        "Le motif d'override doit faire au moins "
                        "10 caractères et être circonstancié "
                        "(ex. n° passeport, nom client, justificatif)."
                    ),
                },
            )
        # Audit log immédiat — la transaction n'est pas encore créée,
        # donc entity_id reste NULL ; le hash chain de la transaction
        # tracera ensuite la liaison via timestamp + user_id.
        db.add(
            AuditLog(
                user_id=current_user.id,
                action="cash_cap_override",
                entity="transaction",
                entity_id=None,
                data={
                    "cash_total_eur": float(cash_check.cash_total_eur),
                    "cap_eur": float(cash_check.cap_eur),
                    "is_tourist": cash_check.is_tourist,
                    "reason": reason,
                    "client_uuid": (
                        str(request.client_uuid)
                        if request.client_uuid
                        else None
                    ),
                },
            )
        )
        logger.warning(
            "cash_cap_override by user=%s total=%.2f€ cap=%.2f€ is_tourist=%s",
            current_user.id,
            cash_check.cash_total_eur,
            cash_check.cap_eur,
            cash_check.is_tourist,
        )

    transaction = await pos_service.create_transaction(
        user_id=current_user.id,
        items=request.items,
        payments=request.payments,
        client_id=request.client_id,
        cashier_id=request.cashier_id,
        client_uuid=request.client_uuid,
        is_invoice=request.is_invoice,
        client_siret=request.client_siret,
        client_company_name=request.client_company_name,
        client_billing_address=request.client_billing_address,
        template_id=request.template_id,
    )

    # If create_transaction returned the existing row (idempotent replay
    # via client_uuid), the hash chain is already set and the analytics
    # events were emitted on the first call. Skip both.
    is_replay = (
        request.client_uuid is not None
        and transaction.hash_chain
    )
    if is_replay:
        return {
            "id": str(transaction.id),
            "transaction_id": str(transaction.id),
            "transaction_number": transaction.transaction_number,
            "total_ttc": float(transaction.total_ttc),
            "replayed": True,
        }

    # Generate fiscal hash chain
    await fiscal_service.sign_transaction(transaction)

    # Coupon redemption + analytics events
    await pos_service.finalize_sale(
        transaction,
        coupon_code=request.coupon_code,
        user_id=current_user.id,
    )

    return {
        "id": str(transaction.id),
        "transaction_id": str(transaction.id),
        "transaction_number": transaction.transaction_number,
        "total_ttc": float(transaction.total_ttc),
    }


_COUPON_ERROR_MESSAGES = {
    "not_found": "Code inconnu.",
    "inactive": "Ce code a été désactivé.",
    "redeemed": "Ce code a déjà été utilisé.",
    "expired": "Ce code est expiré.",
    "not_yet_valid": "Ce code n'est pas encore valable.",
    "no_client": "Ce code est nominatif — sélectionne d'abord la cliente.",
    "wrong_client": "Ce code appartient à une autre cliente.",
}


@router.post("/coupons/validate")
async def validate_pos_coupon(
    payload: ValidateCouponRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Read-only check for the cashier preview before validation."""
    from app.services.coupon import CouponError, validate_coupon

    try:
        preview = await validate_coupon(
            db,
            code=payload.code,
            cart_total=payload.cart_total,
            client_id=payload.client_id,
        )
    except CouponError as exc:
        msg = _COUPON_ERROR_MESSAGES.get(str(exc), "Code refusé.")
        raise HTTPException(status_code=409, detail=msg)

    return {
        "code": preview.code,
        "discount_type": preview.discount_type,
        "discount_value": preview.discount_value,
        "discount_amount": preview.discount_amount,
        "new_total": preview.new_total,
        "source": preview.source,
        "valid_until": preview.valid_until.isoformat(),
    }


@router.get("/transactions")
async def list_transactions(
    skip: int = 0,
    limit: int = 50,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List recent transactions."""
    pos_service = PosService(db)
    transactions = await pos_service.list_transactions(skip=skip, limit=limit)
    return transactions


@router.get("/transactions/{transaction_id}")
async def get_transaction(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get transaction details."""
    pos_service = PosService(db)
    transaction = await pos_service.get_transaction(transaction_id)
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction not found")
    return transaction


@router.post("/drawer/open")
async def open_drawer(
    request: OpenDrawerRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Open cash drawer for the day."""
    pos_service = PosService(db)
    breakdown = (
        [item.model_dump() for item in request.opening_breakdown]
        if request.opening_breakdown
        else None
    )
    drawer = await pos_service.open_drawer(
        current_user.id,
        request.opening_amount,
        cashier_id=request.cashier_id,
        opening_breakdown=breakdown,
    )

    from app.models.events import EventSource, EventType
    await EventService(db).emit(
        EventType.cashier_session_opened,
        source=EventSource.pos,
        user_id=current_user.id,
        meta={
            "drawer_id": str(drawer.id),
            "cashier_id": str(request.cashier_id) if request.cashier_id else None,
            "opening_amount": float(drawer.opening_amount),
        },
    )

    return {
        "drawer_id": str(drawer.id),
        "opening_amount": float(drawer.opening_amount),
    }


@router.post("/drawer/close")
async def close_drawer(
    request: CloseDrawerRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Close cash drawer and generate Z report."""
    pos_service = PosService(db)
    fiscal_service = FiscalService(db)

    closing_breakdown = (
        [item.model_dump() for item in request.closing_breakdown]
        if request.closing_breakdown
        else None
    )
    drawer = await pos_service.close_drawer(
        current_user.id,
        request.closing_amount,
        cashier_id=request.cashier_id,
        closing_breakdown=closing_breakdown,
        closing_note=request.closing_note,
        allowed_discrepancy_override=request.allowed_discrepancy_override,
    )
    z_report = await fiscal_service.generate_z_report(
        drawer, current_user.id, cashier_id=request.cashier_id
    )

    from app.models.events import EventSource, EventType
    discrepancy = (
        float(drawer.closing_amount) - float(drawer.expected_amount)
        if drawer.expected_amount is not None and drawer.closing_amount is not None
        else None
    )
    await EventService(db).emit(
        EventType.cashier_session_closed,
        source=EventSource.pos,
        user_id=current_user.id,
        meta={
            "drawer_id": str(drawer.id),
            "cashier_id": str(drawer.cashier_id) if drawer.cashier_id else None,
            "z_report_number": z_report.report_number,
            "discrepancy": discrepancy,
            "transaction_count": z_report.transaction_count,
        },
    )

    return {
        "drawer_id": str(drawer.id),
        "z_report_number": z_report.report_number,
        "total_sales": float(z_report.total_sales),
        "total_refunds": float(z_report.total_refunds),
        "total_net": float(z_report.total_net),
        "transaction_count": z_report.transaction_count,
        "difference": float(drawer.closing_amount - drawer.expected_amount)
        if drawer.expected_amount
        else 0,
    }


@router.get("/drawer/current")
async def get_current_drawer(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get the currently open drawer."""
    pos_service = PosService(db)
    drawer = await pos_service.get_open_drawer()
    if not drawer:
        return {"open": False}
    return {
        "open": True,
        "drawer_id": str(drawer.id),
        "opening_amount": float(drawer.opening_amount),
    }


@router.get("/z-reports")
async def list_z_reports(
    skip: int = 0,
    limit: int = 30,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List Z reports."""
    fiscal_service = FiscalService(db)
    reports = await fiscal_service.list_z_reports(skip=skip, limit=limit)
    return reports


class CBInitiateRequest(BaseModel):
    amount: float
    description: str = "Vente Vintiz"


class ResendRequest(BaseModel):
    channel: str  # 'email' or 'sms'
    # Optional ad-hoc recipient (walk-in customer with no CRM record).
    # When set, overrides the client's stored email/phone on the
    # transaction. When omitted, the linked client's email/phone is used
    # as before.
    to: str | None = None


# ---------------------------------------------------------------------------
# CB / SumUp endpoints
# ---------------------------------------------------------------------------

@router.post("/payments/cb/initiate")
async def initiate_cb_payment(
    request: CBInitiateRequest,
    current_user: User = Depends(get_current_user),
):
    """Initiate a SumUp card checkout. Returns checkout_id for polling."""
    from app.services.sumup_service import SumUpService
    svc = SumUpService()
    result = await svc.create_checkout(
        amount=request.amount,
        description=request.description,
    )
    return result


@router.get("/payments/cb/{checkout_id}/status")
async def get_cb_payment_status(
    checkout_id: str,
    current_user: User = Depends(get_current_user),
):
    """Poll the status of a SumUp checkout."""
    from app.services.sumup_service import SumUpService
    svc = SumUpService()
    result = await svc.get_checkout_status(checkout_id)
    return result


@router.delete("/payments/cb/{checkout_id}")
async def cancel_cb_payment(
    checkout_id: str,
    current_user: User = Depends(get_current_user),
):
    """Cancel a pending SumUp checkout."""
    from app.services.sumup_service import SumUpService
    svc = SumUpService()
    ok = await svc.cancel_checkout(checkout_id)
    return {"cancelled": ok}


# ---------------------------------------------------------------------------
# SumUp config endpoint (production only)
# ---------------------------------------------------------------------------

@router.get("/payments/cb/config")
async def get_sumup_config(current_user: User = Depends(get_current_user)):
    """Return the current SumUp configuration (keys set, masked merchant
    code, reader id, etc.). Production-only — le mode sandbox/simulation
    a été retiré pour le passage en prod boutique."""
    from app.services.sumup_service import SumUpService
    return SumUpService().describe()


@router.post("/transactions/{transaction_id}/resend")
async def resend_transaction(
    transaction_id: uuid.UUID,
    request: ResendRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(manager_only),
):
    """Resend a transaction receipt by email or SMS.

    Manager-only: the receipt payload contains client PII (name, email,
    purchased items). A staff or magic-link client JWT must not be able to
    pull arbitrary tickets by guessing transaction UUIDs.
    """
    pos_service = PosService(db)
    transaction = await pos_service.get_transaction(transaction_id)
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction introuvable")
    logger.info(
        "Receipt resend requested by user=%s for transaction=%s channel=%s ad_hoc=%s",
        current_user.id, transaction_id, request.channel, bool(request.to),
    )

    client = transaction.get("client") or {}
    ad_hoc_to = (request.to or "").strip() or None
    # Greeting derived from the linked client first name when present;
    # falls back to a neutral wording for ad-hoc recipients.
    greeting_name = client.get("first_name") if client else None

    if not ad_hoc_to and not client:
        raise HTTPException(
            status_code=400,
            detail="Aucun client associe a cette transaction — fournissez 'to'",
        )

    ticket_num = transaction["transaction_number"]
    total = transaction["total_ttc"]
    items_text = "\n".join(
        f"  - {item['name']} x{item['quantity']} : {item['unit_price']:.2f} EUR"
        for item in transaction.get("items", [])
    )

    if request.channel == "email":
        recipient = ad_hoc_to or client.get("email")
        if not recipient:
            raise HTTPException(
                status_code=400,
                detail="Adresse email manquante (ni client, ni 'to' fourni)",
            )
        from app.services.email_gateway import (
            EmailDeliveryError,
            EmailMessage,
            send_email as _gateway_send,
        )

        salutation = f"Bonjour {greeting_name}" if greeting_name else "Bonjour"
        body_text = (
            f"{salutation},\n\n"
            f"Voici le recu de votre achat chez Vintiz.\n\n"
            f"Ticket #{ticket_num}\n"
            f"Articles :\n{items_text}\n\n"
            f"Total TTC : {total:.2f} EUR\n\n"
            f"Merci de votre visite !\nVintiz — Boutique de seconde main premium"
        )
        body_html = "<pre style=\"font-family: monospace\">" + body_text + "</pre>"

        try:
            outcome = _gateway_send(EmailMessage(
                to=recipient,
                to_name=greeting_name,
                subject=f"Votre reçu Vintiz #{ticket_num}",
                html=body_html,
                text=body_text,
            ))
        except EmailDeliveryError:
            logger.exception("Failed to send receipt email for transaction %s",
                             transaction_id)
            raise HTTPException(
                status_code=502,
                detail="L'envoi de l'email a échoué. Réessayez plus tard.",
            )
        logger.info("Receipt email %s for transaction %s via %s",
                    outcome.status, transaction_id, outcome.backend)
        simulated = outcome.status != "sent"
        return {
            "success": True,
            "status": outcome.status,
            "simulated": simulated,
            "channel": "email",
            "to": recipient,
            "backend": outcome.backend,
            "message": (
                f"Email envoyé à {recipient}"
                if not simulated
                else (
                    f"⚠ Email simulé (provider non configuré). "
                    f"Le destinataire {recipient} N'A PAS reçu le ticket. "
                    f"Configurez Brevo ou SMTP dans /settings > Communication."
                )
            ),
        }

    elif request.channel == "sms":
        recipient = ad_hoc_to or client.get("phone")
        if not recipient:
            raise HTTPException(
                status_code=400,
                detail="Numéro de téléphone manquant (ni client, ni 'to' fourni)",
            )
        if settings.TWILIO_ACCOUNT_SID and settings.TWILIO_AUTH_TOKEN and settings.TWILIO_FROM:
            try:
                from twilio.rest import Client as TwilioClient
                tw = TwilioClient(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
                tw.messages.create(
                    body=f"Vintiz - Ticket #{ticket_num} - Total {total:.2f}EUR. Merci !",
                    from_=settings.TWILIO_FROM,
                    to=recipient,
                )
                logger.info("Receipt SMS sent for transaction %s", transaction_id)
                return {
                    "success": True,
                    "status": "sent",
                    "simulated": False,
                    "channel": "sms",
                    "to": recipient,
                    "backend": "twilio",
                    "message": f"SMS envoyé au {recipient}",
                }
            except Exception as exc:  # noqa: BLE001 — Twilio raises many subclasses
                logger.exception("Failed to send receipt SMS for transaction %s", transaction_id)
                # Surface the Twilio error class + first line of the
                # message so the manager sees the real cause (account
                # suspended, invalid number, geo-permission missing…)
                detail = type(exc).__name__
                msg = str(exc).splitlines()[0] if str(exc) else ""
                raise HTTPException(
                    status_code=502,
                    detail=f"L'envoi SMS a échoué via Twilio ({detail}: {msg[:120]})",
                )
        else:
            logger.warning(
                "Receipt SMS simulated for transaction %s — Twilio not configured "
                "(SID set=%s, TOKEN set=%s, FROM set=%s)",
                transaction_id,
                bool(settings.TWILIO_ACCOUNT_SID),
                bool(settings.TWILIO_AUTH_TOKEN),
                bool(settings.TWILIO_FROM),
            )
            return {
                "success": True,
                "status": "simulated",
                "simulated": True,
                "channel": "sms",
                "to": recipient,
                "backend": "none",
                "message": (
                    f"⚠ SMS simulé (Twilio non configuré). "
                    f"Le destinataire {recipient} N'A PAS reçu le ticket. "
                    f"Renseignez TWILIO_ACCOUNT_SID / TWILIO_AUTH_TOKEN / TWILIO_FROM."
                ),
            }
    else:
        raise HTTPException(status_code=400, detail="Canal invalide (email ou sms)")


@router.post("/transactions/{transaction_id}/print")
async def print_transaction_receipt(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Send the receipt to the MUNBYN ESC/POS printer (TCP 9100)."""
    from sqlalchemy import select
    from sqlalchemy.orm import selectinload

    from app.models.pos import PaymentMethod, Transaction
    from app.services import escpos_service
    from app.services.hardware_config import load_config

    result = await db.execute(
        select(Transaction)
        .options(selectinload(Transaction.items), selectinload(Transaction.payments))
        .where(Transaction.id == transaction_id)
    )
    transaction = result.scalar_one_or_none()
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction introuvable")

    cfg = load_config()
    rp = cfg["receipt_printer"]
    if not rp.get("enabled"):
        raise HTTPException(status_code=400, detail="Imprimante de recus desactivee dans les parametres")
    host = rp.get("host") or ""
    port = int(rp.get("port") or 9100)
    if not host:
        raise HTTPException(status_code=400, detail="Adresse IP de l'imprimante non configuree")

    try:
        escpos_service.print_receipt(
            transaction,
            host=host,
            port=port,
            width=int(rp.get("width_chars") or 42),
            cut=bool(rp.get("cut_paper", True)),
        )
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=502, detail=f"Imprimante injoignable : {exc}") from exc

    # Auto-kick drawer if cash payment and drawer enabled. The kick is best
    # effort (the printer was reachable just above), but a silent failure
    # would leave the drawer closed on a cash sale without alerting the
    # cashier — accounting risk. Surface the outcome in the response and
    # log the full traceback if the kick fails.
    drawer_kick_ok: bool | None = None
    drawer_error: str | None = None
    drawer_cfg = cfg["cash_drawer"]
    if drawer_cfg.get("enabled") and drawer_cfg.get("kick_on_cash"):
        has_cash = any(
            (p.method == PaymentMethod.cash)
            for p in (transaction.payments or [])
        )
        if has_cash:
            try:
                escpos_service.kick_drawer(
                    host,
                    port,
                    pin=int(drawer_cfg.get("kick_pin") or 0),
                    on_time=int(drawer_cfg.get("on_time_ms") or 50),
                    off_time=int(drawer_cfg.get("off_time_ms") or 250),
                )
                drawer_kick_ok = True
            except Exception as exc:  # noqa: BLE001
                drawer_kick_ok = False
                drawer_error = str(exc)
                logger.exception(
                    "Cash drawer kick failed for transaction %s on %s:%s",
                    transaction_id, host, port,
                )

    response: dict = {"success": True, "transaction_id": str(transaction_id)}
    if drawer_kick_ok is not None:
        response["drawer_kicked"] = drawer_kick_ok
        if drawer_error:
            response["drawer_error"] = drawer_error
    return response


@router.get("/transactions/{transaction_id}/escpos")
async def get_transaction_escpos(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    kick_drawer: bool = False,
):
    """Return the raw ESC/POS byte stream for the receipt.

    Used by the WebUSB flow on the cashier tablet (Lenovo Idea Tab Pro):
    the front fetches these bytes and pipes them to the MUNBYN directly
    over USB-OTG, bypassing the backend's TCP socket. Same ``build_receipt``
    helper as the network path, so the printed output is identical.

    Pass ``kick_drawer=true`` to append the ``ESC p`` drawer pulse at the
    end of the payload (used on cash sales when the drawer is wired to
    the printer's RJ-12 port).
    """
    from sqlalchemy import select
    from sqlalchemy.orm import selectinload
    from fastapi.responses import Response

    from app.models.pos import Transaction
    from app.services import escpos_service
    from app.services.hardware_config import load_config

    result = await db.execute(
        select(Transaction)
        .options(selectinload(Transaction.items), selectinload(Transaction.payments))
        .where(Transaction.id == transaction_id)
    )
    transaction = result.scalar_one_or_none()
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction introuvable")

    cfg = load_config()
    rp = cfg["receipt_printer"]
    payload = escpos_service.build_receipt(
        transaction,
        width=int(rp.get("width_chars") or 42),
        cut=bool(rp.get("cut_paper", True)),
    )
    if kick_drawer:
        drawer_cfg = cfg["cash_drawer"]
        payload += escpos_service.build_drawer_kick(
            pin=int(drawer_cfg.get("kick_pin") or 0),
            on_time=int(drawer_cfg.get("on_time_ms") or 50),
            off_time=int(drawer_cfg.get("off_time_ms") or 250),
        )
    return Response(
        content=bytes(payload),
        media_type="application/octet-stream",
        headers={
            "Content-Disposition": f'attachment; filename="receipt-{transaction_id}.bin"',
            "Cache-Control": "no-store",
        },
    )


@router.get(
    "/transactions/{transaction_id}/invoice.pdf",
    dependencies=[Depends(manager_only)],
)
async def get_transaction_invoice_pdf(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Stream the B2B invoice PDF for an ``is_invoice=True`` transaction.

    Manager only. The template snapshot pointed by ``template_id`` is used
    so the document reproduces the historical document — editing the
    template afterwards never alters past invoices.
    """
    from fastapi.responses import Response

    from app.models.pos import Transaction
    from app.models.receipt_template import ReceiptKind, ReceiptTemplate
    from app.services.invoice_pdf import generate_invoice_pdf

    row = (
        await db.execute(
            select(Transaction).where(Transaction.id == transaction_id)
        )
    ).scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="Transaction introuvable")
    if not row.is_invoice:
        raise HTTPException(
            status_code=400,
            detail="Cette transaction n'est pas une facture B2B.",
        )

    template = None
    if row.template_id is not None:
        template = (
            await db.execute(
                select(ReceiptTemplate).where(ReceiptTemplate.id == row.template_id)
            )
        ).scalar_one_or_none()
    if template is None:
        # Fallback to the active default invoice template
        template = (
            await db.execute(
                select(ReceiptTemplate)
                .where(
                    ReceiptTemplate.kind == ReceiptKind.invoice,
                    ReceiptTemplate.is_default.is_(True),
                    ReceiptTemplate.is_active.is_(True),
                )
                .limit(1)
            )
        ).scalar_one_or_none()

    pdf_bytes = generate_invoice_pdf(row, template=template)
    label = (
        f"FACT-{row.created_at.year}-{row.invoice_number:06d}"
        if row.invoice_number is not None and row.created_at
        else f"FACT-{row.transaction_number:06d}"
    )
    headers = {
        "Content-Disposition": f'attachment; filename="{label}.pdf"',
    }
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers=headers,
    )


@router.get("/transactions/{transaction_id}/receipt")
async def get_transaction_receipt(
    transaction_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate and return receipt text for a transaction."""
    from sqlalchemy import select
    from app.models.client import Client, LoyaltyTransaction, LoyaltyTxType
    from app.models.pos import Transaction
    from app.models.receipt_template import ReceiptKind, ReceiptTemplate
    from app.services.receipt import ReceiptService

    result = await db.execute(
        select(Transaction).where(Transaction.id == transaction_id)
    )
    transaction = result.scalar_one_or_none()
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction not found")

    # Resolve the template snapshot (NF525 — historical receipts must keep the
    # template they were signed with). Fallback to the active default for the
    # transaction's kind when ``template_id`` is unset.
    template = None
    target_kind = (
        ReceiptKind.invoice if transaction.is_invoice else ReceiptKind.ticket
    )
    if transaction.template_id is not None:
        template = (
            await db.execute(
                select(ReceiptTemplate).where(
                    ReceiptTemplate.id == transaction.template_id
                )
            )
        ).scalar_one_or_none()
    if template is None:
        template = (
            await db.execute(
                select(ReceiptTemplate)
                .where(
                    ReceiptTemplate.kind == target_kind,
                    ReceiptTemplate.is_default.is_(True),
                    ReceiptTemplate.is_active.is_(True),
                )
                .limit(1)
            )
        ).scalar_one_or_none()

    # Resolve fidelity context (PR1): the footer surfaces member info or
    # a "would-have-earned" line for non-members.
    client = None
    loyalty_account = None
    points_earned = None
    if transaction.client_id is not None:
        client_row = await db.execute(
            select(Client).where(Client.id == transaction.client_id)
        )
        client = client_row.scalar_one_or_none()
        if client and client.loyalty_account is not None:
            loyalty_account = client.loyalty_account
            earn_row = await db.execute(
                select(LoyaltyTransaction.points)
                .where(
                    LoyaltyTransaction.account_id == loyalty_account.id,
                    LoyaltyTransaction.tx_type == LoyaltyTxType.earn,
                    LoyaltyTransaction.description == f"Sale #{transaction.transaction_number}",
                )
            )
            points_earned = earn_row.scalar_one_or_none() or 0

    receipt_service = ReceiptService()
    receipt_text = receipt_service.generate_receipt_text(
        transaction,
        client=client,
        loyalty_account=loyalty_account,
        points_earned_on_sale=points_earned,
        template=template,
    )

    return {
        "receipt_text": receipt_text,
        "transaction_id": str(transaction_id),
    }


# ---------------------------------------------------------------------------
# Cashier identification (PIN-based) — tickets P1-002 + P1-014
# ---------------------------------------------------------------------------


@router.post(
    "/cashier/set-pin",
    dependencies=[Depends(manager_only)],
)
async def set_cashier_pin(
    request: CashierPinSetRequest,
    db: AsyncSession = Depends(get_db),
):
    """Set or replace a 4-digit POS PIN for a user. Manager only."""
    result = await db.execute(select(User).where(User.id == request.user_id))
    user = result.scalar_one_or_none()
    if user is None:
        raise HTTPException(status_code=404, detail="User not found")
    cashier_service = CashierService(db)
    await cashier_service.set_pin(user, request.pin)
    return {"user_id": str(user.id), "has_pin": True}


@router.post(
    "/cashier/clear-pin",
    dependencies=[Depends(manager_only)],
)
async def clear_cashier_pin(
    request: CashierPinClearRequest,
    db: AsyncSession = Depends(get_db),
):
    """Remove a user's POS PIN. Manager only."""
    result = await db.execute(select(User).where(User.id == request.user_id))
    user = result.scalar_one_or_none()
    if user is None:
        raise HTTPException(status_code=404, detail="User not found")
    cashier_service = CashierService(db)
    await cashier_service.clear_pin(user)
    return {"user_id": str(user.id), "has_pin": False}


@router.post("/cashier/login", response_model=CashierResponse)
async def cashier_pin_login(
    request: CashierPinLoginRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Identify a cashier from their 4-digit PIN.

    Requires a valid JWT (the iPad is logged in as a manager). Returns
    the cashier's id and role so the POS UI can stamp subsequent
    transactions / drawer events.
    """
    cashier_service = CashierService(db)
    cashier = await cashier_service.authenticate_pin(request.pin)
    logger.info(
        "Cashier PIN login: cashier_id=%s by_user=%s",
        cashier.id,
        current_user.id,
    )
    return CashierResponse(
        id=cashier.id,
        username=cashier.username,
        role=cashier.role.value,
    )


@router.get(
    "/cashier/list",
    response_model=list[CashierWithPinStatusResponse],
    dependencies=[Depends(manager_only)],
)
async def list_cashiers(db: AsyncSession = Depends(get_db)):
    """List all users with their PIN status. Manager only."""
    cashier_service = CashierService(db)
    return await cashier_service.list_with_pin_status()


# ---------------------------------------------------------------------------
# Refunds (P1-010 + P1-016) — partial / full, settled in cash, card or avoir
# ---------------------------------------------------------------------------


class RefundLineRequest(BaseModel):
    transaction_item_id: uuid.UUID
    quantity: int


class RefundRequest(BaseModel):
    items: list[RefundLineRequest]
    refund_method: str  # cash | card | cheque | avoir
    cashier_id: uuid.UUID | None = None
    reason: str | None = None


@router.post("/transactions/{transaction_id}/refund")
async def refund_transaction(
    transaction_id: uuid.UUID,
    request: RefundRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Issue a partial or full refund of a sale.

    Refunded products are returned to display status. The refund total can
    be settled in cash, on card (record only — SumUp call is a TODO), or as
    store credit on the customer's avoir balance.
    """
    refund_service = RefundService(db)
    fiscal_service = FiscalService(db)

    refund_tx = await refund_service.refund_transaction(
        original_tx_id=transaction_id,
        items=[
            RefundLineInput(line.transaction_item_id, line.quantity)
            for line in request.items
        ],
        refund_method=request.refund_method,
        user_id=current_user.id,
        cashier_id=request.cashier_id,
        reason=request.reason,
    )
    await fiscal_service.sign_transaction(refund_tx)

    # Emit a product.refunded event per refunded item (P1-003).
    from app.models.events import EventSource, EventType
    events = EventService(db)
    for item in (refund_tx.items or []):
        if item.product_id is None:
            continue
        await events.emit(
            EventType.product_refunded,
            source=EventSource.pos,
            customer_id=refund_tx.client_id,
            product_id=item.product_id,
            transaction_id=refund_tx.id,
            user_id=current_user.id,
            meta={
                "quantity": int(item.quantity),
                "refund_method": request.refund_method,
                "reason": request.reason,
                "original_transaction_id": str(refund_tx.original_transaction_id),
            },
        )

    return {
        "id": str(refund_tx.id),
        "transaction_number": refund_tx.transaction_number,
        "transaction_type": refund_tx.transaction_type.value,
        "original_transaction_id": str(refund_tx.original_transaction_id)
        if refund_tx.original_transaction_id
        else None,
        "total_ttc": float(refund_tx.total_ttc),
        "refund_method": request.refund_method,
        "hash_chain": refund_tx.hash_chain,
    }


# ---------------------------------------------------------------------------
# Loyalty subscription + client identification (PR1)
# ---------------------------------------------------------------------------


class LoyaltySubscribeRequest(BaseModel):
    first_name: str
    last_name: str
    email: str
    postal_code: str | None = None
    accept_terms: bool
    optin_newsletter: bool = False
    optin_profiling: bool = False
    mode_override: str | None = None  # null = use admin config


@router.post(
    "/loyalty/subscribe",
    status_code=201,
    dependencies=[Depends(manager_only)],
)
async def subscribe_loyalty(
    request: LoyaltySubscribeRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Enrol a client in the loyalty programme from the POS.

    409 with ``existing_membership_number`` on duplicate email — the POS
    UI proposes to fuse instead of creating a second account.
    """
    if not request.accept_terms:
        raise HTTPException(status_code=400, detail="Conditions a accepter")

    from app.services.loyalty import LoyaltyDuplicateError, subscribe
    from app.services.loyalty_config import get_subscription_config

    config = await get_subscription_config(db)
    mode = request.mode_override or config.mode

    try:
        client, account = await subscribe(
            db,
            first_name=request.first_name,
            last_name=request.last_name,
            email=request.email,
            postal_code=request.postal_code,
            mode=mode,
            optin_newsletter=request.optin_newsletter,
            optin_profiling=request.optin_profiling,
            user_id=current_user.id,
        )
    except LoyaltyDuplicateError as exc:
        await db.rollback()
        raise HTTPException(
            status_code=409,
            detail={
                "code": "duplicate_email",
                "existing_membership_number": exc.membership_number,
                "client_id": str(exc.client_id),
            },
        )
    await db.commit()
    return {
        "client_id": str(client.id),
        "membership_number": account.membership_number,
        "mode_applied": mode,
        "expires_at": client.loyalty_expires_at.isoformat()
        if client.loyalty_expires_at
        else None,
    }


@router.get("/companion/non-member")
async def pos_companion_non_member(
    cart_total_cents: int = 0,
    current_user: User = Depends(get_current_user),
):
    """Companion payload for a non-identified client (no client_id).

    Used by the POS to surface a "Vous gagneriez X pts en adhérant" banner
    while inviting the cashier to subscribe the customer to the loyalty
    program. Returns the points the customer would earn IF they were members.
    """
    from app.services.pos_companion import _points_to_credit

    cents = max(0, int(cart_total_cents))
    return {
        "client": None,
        "loyalty": {
            "active": False,
            "would_earn": _points_to_credit(cents),
            "points_per_euro": 1,
        },
        "cta": {
            "label": "Proposer la carte de fidélité",
            "incentive": (
                f"Cette cliente gagnerait {_points_to_credit(cents)} pts en adhérant."
                if cents > 0
                else "Adhésion gratuite — 1 € dépensé = 1 pt."
            ),
        },
    }


@router.get("/clients/{client_id}/companion")
async def pos_companion(
    client_id: uuid.UUID,
    cart_total_cents: int = 0,
    items: str | None = None,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Cart-aware up-sell payload for the POS companion panel (PR4).

    ``items`` is a comma-separated list of product UUIDs already in the
    cart. Empty cart is supported — the suggestions block is just empty.
    """
    cart_product_ids: list[uuid.UUID] = []
    if items:
        for raw in items.split(","):
            raw = raw.strip()
            if not raw:
                continue
            try:
                cart_product_ids.append(uuid.UUID(raw))
            except ValueError:
                continue

    from app.services.pos_companion import companion_payload

    try:
        payload = await companion_payload(
            db,
            client_id=client_id,
            cart_total_cents=max(0, int(cart_total_cents)),
            cart_product_ids=cart_product_ids,
        )
    except LookupError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    return payload


def _serialize_client_for_pos(client) -> dict:
    loyalty = client.loyalty_account
    return {
        "client_id": str(client.id),
        "first_name": client.first_name,
        "last_name": client.last_name,
        "email": client.email,
        "phone": client.phone,
        "postal_code": getattr(client, "postal_code", None),
        "membership_number": loyalty.membership_number if loyalty else None,
        "loyalty": {
            "active": loyalty is not None,
            "points": loyalty.points if loyalty else 0,
            "expires_at": client.loyalty_expires_at.isoformat()
            if client.loyalty_expires_at
            else None,
        },
    }


@router.get("/clients/identify")
async def identify_client_pos(
    q: str | None = None,
    postal_code: str | None = None,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Resolve a client from a free-form input (membership / email / phone)
    OR from a postal_code + name combination when no other identifier is at
    hand. Multiple matches are returned as ``{matches: [...]}`` so the
    cashier can pick.
    """
    from app.models.client import Client, LoyaltyAccount  # noqa: F401
    from app.services.membership_id import (
        is_membership_number,
        lookup_by_membership_number,
    )
    from sqlalchemy import or_, func as _func

    q_clean = (q or "").strip()
    postal_clean = (postal_code or "").strip()
    if not q_clean and not postal_clean:
        raise HTTPException(status_code=400, detail="empty query")

    client = None

    # Path 1 — direct identifier (membership / email / phone)
    if q_clean and not postal_clean:
        if is_membership_number(q_clean):
            client = await lookup_by_membership_number(db, q_clean)
        elif "@" in q_clean:
            row = await db.execute(select(Client).where(Client.email == q_clean.lower()))
            client = row.scalar_one_or_none()
        elif q_clean.replace("+", "").replace(" ", "").isdigit():
            row = await db.execute(select(Client).where(Client.phone == q_clean))
            client = row.scalar_one_or_none()

    # Path 2 — postal code + name. Returns a list when ambiguous.
    if client is None and postal_clean:
        like = f"%{q_clean.lower()}%" if q_clean else "%"
        stmt = (
            select(Client)
            .where(Client.postal_code == postal_clean)
            .where(
                or_(
                    _func.lower(_func.coalesce(Client.last_name, "")).like(like),
                    _func.lower(_func.coalesce(Client.first_name, "")).like(like),
                )
            )
            .order_by(Client.created_at.desc())
            .limit(20)
        )
        rows = (await db.execute(stmt)).scalars().all()
        if len(rows) == 0:
            raise HTTPException(status_code=404, detail="client_not_found")
        if len(rows) == 1:
            client = rows[0]
        else:
            return {"matches": [_serialize_client_for_pos(c) for c in rows]}

    if client is None:
        raise HTTPException(status_code=404, detail="client_not_found")

    return _serialize_client_for_pos(client)


# ---------------------------------------------------------------------------
# Cash movements (PR 3/6) — entrée/sortie cash en cours de journée
# ---------------------------------------------------------------------------


@router.post("/cash-movements")
async def create_cash_movement(
    request: CashMovementRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Record a mid-day cash flow on the currently open drawer.

    - ``out / bank_deposit`` — manager removes cash to deposit at the bank
    - ``out / supplier_payment`` — supplier paid in cash
    - ``out / personal_withdrawal`` — owner takes a withdrawal
    - ``in  / float_top_up`` — extra change brought in from the safe
    - ``in / out / other`` — misc, with a free-text ``note``

    The Z report aggregates these into the expected total at closing so
    a deposit doesn't appear as a discrepancy. Append-only — no PUT/DELETE.
    """
    from app.models.cash_movement import (
        CashMovement,
        CashMovementDirection,
        CashMovementReason,
    )

    pos_service = PosService(db)
    drawer = await pos_service.get_open_drawer()
    if drawer is None:
        raise HTTPException(
            status_code=400,
            detail="Aucune caisse ouverte — impossible d'enregistrer un mouvement.",
        )

    try:
        direction = CashMovementDirection(request.direction)
    except ValueError:
        raise HTTPException(
            status_code=400, detail="direction doit être 'in' ou 'out'."
        )
    try:
        reason = CashMovementReason(request.reason)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail=(
                "reason doit être l'une de : "
                + ", ".join(r.value for r in CashMovementReason)
            ),
        )
    if Decimal(str(request.amount)) <= 0:
        raise HTTPException(status_code=400, detail="amount doit être strictement positif.")

    movement = CashMovement(
        drawer_id=drawer.id,
        direction=direction,
        amount=float(request.amount),
        reason=reason,
        note=request.note,
        user_id=current_user.id,
        cashier_id=request.cashier_id or drawer.cashier_id,
    )
    db.add(movement)
    await db.flush()
    await db.refresh(movement)
    return {
        "id": str(movement.id),
        "drawer_id": str(movement.drawer_id),
        "direction": movement.direction.value,
        "amount": float(movement.amount),
        "reason": movement.reason.value,
        "note": movement.note,
        "user_id": str(movement.user_id),
        "cashier_id": str(movement.cashier_id) if movement.cashier_id else None,
        "created_at": movement.created_at.isoformat() if movement.created_at else None,
    }


@router.get("/cash-movements")
async def list_cash_movements(
    drawer_id: uuid.UUID | None = None,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List cash movements, optionally scoped to a drawer (default: current)."""
    from sqlalchemy import select as _select

    from app.models.cash_movement import CashMovement

    target_drawer_id = drawer_id
    if target_drawer_id is None:
        pos_service = PosService(db)
        drawer = await pos_service.get_open_drawer()
        if drawer is None:
            return {"drawer_id": None, "movements": []}
        target_drawer_id = drawer.id

    rows = (
        await db.execute(
            _select(CashMovement)
            .where(CashMovement.drawer_id == target_drawer_id)
            .order_by(CashMovement.created_at.asc())
        )
    ).scalars().all()
    return {
        "drawer_id": str(target_drawer_id),
        "movements": [
            {
                "id": str(m.id),
                "direction": m.direction.value,
                "amount": float(m.amount),
                "reason": m.reason.value,
                "note": m.note,
                "cashier_id": str(m.cashier_id) if m.cashier_id else None,
                "created_at": m.created_at.isoformat() if m.created_at else None,
            }
            for m in rows
        ],
    }


# ---------------------------------------------------------------------------
# Payment attempts (PR 3/6) — log centralisé de toutes les tentatives
# ---------------------------------------------------------------------------


@router.post("/payment-attempts")
async def log_payment_attempt(
    request: PaymentAttemptRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Persist (or update) a payment attempt — covers the full lifecycle:
    pending → succeeded / failed / cancelled.

    Pas de vente → pas de Transaction NF525 fiscale, mais une PaymentAttempt
    est tracée à chaque initiation pour l'audit. La même attempt peut être
    mise à jour en repassant son ``attempt_id``.
    """
    from app.models.payment_attempt import (
        PaymentAttempt,
        PaymentAttemptStatus,
    )
    from app.models.pos import PaymentMethod

    try:
        method_enum = PaymentMethod(request.method)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail="method invalide (cash | card | cheque | transfer | avoir).",
        )
    try:
        status_enum = PaymentAttemptStatus(request.status)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail="status invalide (pending | succeeded | failed | cancelled).",
        )

    if request.attempt_id is not None:
        existing = (
            await db.execute(
                select(PaymentAttempt).where(PaymentAttempt.id == request.attempt_id)
            )
        ).scalar_one_or_none()
        if existing is None:
            raise HTTPException(status_code=404, detail="Attempt introuvable")
        existing.status = status_enum
        existing.amount = float(request.amount)
        if request.transaction_id is not None:
            existing.transaction_id = request.transaction_id
        if request.error_detail is not None:
            # Defense in depth — un client compromis ou un POS non
            # patché pourrait pousser un payload SumUp brut. Re-redact
            # à la frontière API avant persistance.
            existing.error_detail = redact_sumup_error(request.error_detail)
        if request.cancelled_reason is not None:
            existing.cancelled_reason = request.cancelled_reason
        await db.flush()
        attempt = existing
    else:
        attempt = PaymentAttempt(
            method=method_enum,
            amount=float(request.amount),
            status=status_enum,
            cashier_id=request.cashier_id,
            drawer_id=request.drawer_id,
            transaction_id=request.transaction_id,
            sumup_checkout_id=request.sumup_checkout_id,
            error_detail=redact_sumup_error(request.error_detail)
            if request.error_detail is not None
            else None,
            cancelled_reason=request.cancelled_reason,
        )
        db.add(attempt)
        await db.flush()
        await db.refresh(attempt)

    return {
        "id": str(attempt.id),
        "method": attempt.method.value,
        "amount": float(attempt.amount),
        "status": attempt.status.value,
        "transaction_id": str(attempt.transaction_id) if attempt.transaction_id else None,
        "sumup_checkout_id": attempt.sumup_checkout_id,
        "error_detail": attempt.error_detail,
        "cancelled_reason": attempt.cancelled_reason,
        "created_at": attempt.created_at.isoformat() if attempt.created_at else None,
        "updated_at": attempt.updated_at.isoformat() if attempt.updated_at else None,
    }


# ---------------------------------------------------------------------------
# Z reports — PDF, email, NF525 lock (PR 3/6)
# ---------------------------------------------------------------------------


@router.get(
    "/z-reports/{z_report_id}/pdf",
    dependencies=[Depends(manager_only)],
)
async def get_z_report_pdf(
    z_report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Stream the A4 Z-report PDF (manager only).

    When the Z report is locked the persisted ``pdf_content`` is returned
    byte-identical (NF525 article 88 CGI). Otherwise it's regenerated from
    the live drawer + cash movements + transactions snapshot.
    """
    from fastapi.responses import Response

    from app.models.pos import ZReport
    from app.services.z_report_pdf import generate_z_report_pdf

    z = (
        await db.execute(select(ZReport).where(ZReport.id == z_report_id))
    ).scalar_one_or_none()
    if z is None:
        raise HTTPException(status_code=404, detail="Z report introuvable")

    if z.is_locked and z.pdf_content:
        pdf_bytes = z.pdf_content
        sha = z.pdf_sha256 or ""
    else:
        pdf_bytes = await generate_z_report_pdf(db, z)
        import hashlib as _hl
        sha = _hl.sha256(pdf_bytes).hexdigest()

    headers = {
        "Content-Disposition": f'attachment; filename="Z-{z.report_number:04d}.pdf"',
        "X-Z-Report-SHA256": sha,
        "X-Z-Report-Locked": "1" if z.is_locked else "0",
    }
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers=headers,
    )


class ZReportEmailRequest(BaseModel):
    to: str | None = None  # default: from app_config.email.from_address


@router.post(
    "/z-reports/{z_report_id}/email",
    dependencies=[Depends(manager_only)],
)
async def email_z_report(
    z_report_id: uuid.UUID,
    payload: ZReportEmailRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Email the Z-report PDF (locked or live preview) to the comptable.

    When the report isn't locked yet, the live PDF is regenerated and sent —
    handy to forward an interim copy without committing to NF525 lock.
    """
    fiscal_service = FiscalService(db)
    return await fiscal_service.email_z_report(
        z_report_id, to=payload.to, sender_user_id=current_user.id
    )


@router.post(
    "/z-reports/{z_report_id}/lock",
    dependencies=[Depends(manager_only)],
)
async def lock_z_report(
    z_report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Verrouille intangiblement un Z report (NF525 article 88 CGI).

    Idempotent — un second appel renvoie le même résultat. Une fois
    verrouillé, le ``pdf_content`` + ``pdf_sha256`` sont persistés et toute
    régénération produit le même flux d'octets. Aucun UPDATE ultérieur
    n'est autorisé sur ``total_sales / total_refunds / total_net``.
    """
    fiscal_service = FiscalService(db)
    return await fiscal_service.lock_z_report(z_report_id, user_id=current_user.id)
